// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 200.0000, 0.0000 ],
	[ 200.0000, 100.0000 ],
	[ 0.0000, 100.0000 ],
	[ 0.0000, 0.0000 ] ] });

const ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr001 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 100.0000, 0.0000 ],
	[ 37.5668, 162.7198 ],
	[ 0.0000, 0.0000 ] ] });

const ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr002 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 82.0000, 0.0000 ],
	[ 37.5668, 162.7198 ],
	[ 0.0000, 0.0000 ] ] });

const ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr003 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 82.0000, 0.0000 ],
	[ 65.4940, 44.1762 ],
	[ 0.0000, 0.0000 ] ] });

const ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr004 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 100.0000, 0.0000 ],
	[ 100.0000, 79.0000 ],
	[ 0.0000, 79.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_facePattern_Fa000 = subtract( ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr000, ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr001, ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr002, ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr003, ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr004 );
fig_demoSheetFold2_facePattern = face_fig_demoSheetFold2_facePattern_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_f00_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 200.0000, 0.0000 ],
	[ 200.0000, 100.0000 ],
	[ 0.0000, 100.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_f00_Fa000 = ctr_face_fig_demoSheetFold2_SFG_f00_Fa000_Ctr000;
fig_demoSheetFold2_SFG_f00 = face_fig_demoSheetFold2_SFG_f00_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_f01_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 100.0000 ],
	[ 0.0000, 0.0000 ],
	[ 162.7198, 62.4332 ],
	[ 0.0000, 100.0000 ] ] });

face_fig_demoSheetFold2_SFG_f01_Fa000 = ctr_face_fig_demoSheetFold2_SFG_f01_Fa000_Ctr000;
fig_demoSheetFold2_SFG_f01 = face_fig_demoSheetFold2_SFG_f01_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_f02_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 79.8983, 18.4460 ],
	[ -0.0000, 167.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_f02_Fa000 = ctr_face_fig_demoSheetFold2_SFG_f02_Fa000_Ctr000;
fig_demoSheetFold2_SFG_f02 = face_fig_demoSheetFold2_SFG_f02_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_f03_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 82.0000 ],
	[ 0.0000, 0.0000 ],
	[ 44.1762, 16.5060 ],
	[ 0.0000, 82.0000 ] ] });

face_fig_demoSheetFold2_SFG_f03_Fa000 = ctr_face_fig_demoSheetFold2_SFG_f03_Fa000_Ctr000;
fig_demoSheetFold2_SFG_f03 = face_fig_demoSheetFold2_SFG_f03_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_f04_Fa000_Ctr000 = polygon({ points: [ [ -0.0000, 0.0000 ],
	[ 100.0000, 0.0000 ],
	[ 100.0000, 79.0000 ],
	[ -0.0000, 79.0000 ],
	[ -0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_f04_Fa000 = ctr_face_fig_demoSheetFold2_SFG_f04_Fa000_Ctr000;
fig_demoSheetFold2_SFG_f04 = face_fig_demoSheetFold2_SFG_f04_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_fj00_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 1.6351, 0.0535 ],
	[ 3.2632, 0.2139 ],
	[ 4.8773, 0.4804 ],
	[ 6.4705, 0.8519 ],
	[ 3.8823, 10.5111 ],
	[ 1.9579, 10.1283 ],
	[ 0.0000, 10.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_fj00_Fa000 = ctr_face_fig_demoSheetFold2_SFG_fj00_Fa000_Ctr000;
fig_demoSheetFold2_SFG_fj00 = face_fig_demoSheetFold2_SFG_fj00_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_fj01_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 1.9470, 0.0759 ],
	[ 3.8821, 0.3033 ],
	[ 5.7937, 0.6806 ],
	[ 7.6701, 1.2057 ],
	[ 9.4999, 1.8753 ],
	[ 11.2719, 2.6854 ],
	[ 12.9755, 3.6310 ],
	[ 14.6003, 4.7064 ],
	[ 16.1364, 5.9051 ],
	[ 17.5745, 7.2198 ],
	[ 18.9059, 8.6425 ],
	[ 20.1223, 10.1645 ],
	[ 21.2166, 11.7767 ],
	[ 22.1820, 13.4692 ],
	[ 23.0126, 15.2317 ],
	[ 23.7035, 17.0536 ],
	[ 24.2503, 18.9237 ],
	[ 24.6499, 20.8308 ],
	[ 24.8997, 22.7632 ],
	[ 24.9983, 24.7091 ],
	[ 24.9450, 26.6568 ],
	[ 24.7402, 28.5945 ],
	[ 24.3852, 30.5103 ],
	[ 23.8820, 32.3927 ],
	[ 23.2337, 34.2302 ],
	[ 22.4443, 36.0115 ],
	[ 21.5186, 37.7260 ],
	[ 20.4621, 39.3632 ],
	[ 19.2814, 40.9132 ],
	[ 17.9835, 42.3665 ],
	[ 10.7901, 35.4199 ],
	[ 12.0492, 33.9340 ],
	[ 13.1052, 32.2976 ],
	[ 13.9402, 30.5381 ],
	[ 14.5403, 28.6853 ],
	[ 14.8952, 26.7703 ],
	[ 14.9990, 24.8255 ],
	[ 14.8499, 22.8836 ],
	[ 14.4506, 20.9774 ],
	[ 13.8076, 19.1390 ],
	[ 12.9318, 17.3995 ],
	[ 11.8380, 15.7880 ],
	[ 10.5447, 14.3319 ],
	[ 9.0736, 13.0556 ],
	[ 7.4496, 11.9806 ],
	[ 5.6999, 11.1252 ],
	[ 3.8542, 10.5036 ],
	[ 1.9435, 10.1264 ],
	[ 0.0000, 10.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_fj01_Fa000 = ctr_face_fig_demoSheetFold2_SFG_fj01_Fa000_Ctr000;
fig_demoSheetFold2_SFG_fj01 = face_fig_demoSheetFold2_SFG_fj01_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_fj02_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 1.5262, 0.0466 ],
	[ 3.0467, 0.1863 ],
	[ 4.5559, 0.4186 ],
	[ 6.0480, 0.7426 ],
	[ 3.6288, 10.4456 ],
	[ 1.8280, 10.1118 ],
	[ -0.0000, 10.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_fj02_Fa000 = ctr_face_fig_demoSheetFold2_SFG_fj02_Fa000_Ctr000;
fig_demoSheetFold2_SFG_fj02 = face_fig_demoSheetFold2_SFG_fj02_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_fj03_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 1.9681, 0.0776 ],
	[ 3.9239, 0.3099 ],
	[ 5.8554, 0.6954 ],
	[ 7.7506, 1.2318 ],
	[ 9.5976, 1.9157 ],
	[ 11.3851, 2.7429 ],
	[ 13.1019, 3.7082 ],
	[ 14.7374, 4.8057 ],
	[ 16.2814, 6.0285 ],
	[ 17.7244, 7.3691 ],
	[ 19.0573, 8.8192 ],
	[ 20.2720, 10.3696 ],
	[ 21.3608, 12.0109 ],
	[ 22.3170, 13.7328 ],
	[ 23.1348, 15.5246 ],
	[ 23.8089, 17.3752 ],
	[ 24.3352, 19.2732 ],
	[ 24.7105, 21.2067 ],
	[ 24.9325, 23.1638 ],
	[ 24.9997, 25.1322 ],
	[ 24.9117, 27.0999 ],
	[ 24.6690, 29.0544 ],
	[ 24.2733, 30.9839 ],
	[ 23.7269, 32.8762 ],
	[ 23.0332, 34.7196 ],
	[ 22.1966, 36.5026 ],
	[ 21.2222, 38.2143 ],
	[ 20.1161, 39.8440 ],
	[ 18.8851, 41.3815 ],
	[ 17.5369, 42.8174 ],
	[ 16.0798, 44.1426 ],
	[ 14.5230, 45.3490 ],
	[ 12.8760, 46.4292 ],
	[ 7.7256, 37.8575 ],
	[ 9.3275, 36.7473 ],
	[ 10.7719, 35.4387 ],
	[ 12.0345, 33.9539 ],
	[ 13.0938, 32.3179 ],
	[ 13.9321, 30.5584 ],
	[ 14.5352, 28.7050 ],
	[ 14.8929, 26.7891 ],
	[ 14.9992, 24.8429 ],
	[ 14.8522, 22.8994 ],
	[ 14.4545, 20.9914 ],
	[ 13.8127, 19.1511 ],
	[ 12.9377, 17.4095 ],
	[ 11.8443, 15.7961 ],
	[ 10.5509, 14.3380 ],
	[ 9.0794, 13.0600 ],
	[ 7.4546, 11.9835 ],
	[ 5.7040, 11.1268 ],
	[ 3.8570, 10.5044 ],
	[ 1.9449, 10.1266 ],
	[ 0.0000, 10.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_fj03_Fa000 = ctr_face_fig_demoSheetFold2_SFG_fj03_Fa000_Ctr000;
fig_demoSheetFold2_SFG_fj03 = face_fig_demoSheetFold2_SFG_fj03_Fa000;

const subpax_SFG_f00 =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 10}, fig_demoSheetFold2_SFG_f00 )
		)
	);


const subpax_SFG_f01 =
	translate( [ 206.47047612756302, -3.9620239392897057e-16, 0.8518543427732936, ],
		rotate( [ -1.640715604224463e-17, -0.2617993877991494, 2.160043071267636e-18, ],
			   extrudeLinear( {height: 10}, fig_demoSheetFold2_SFG_f01 )
		)
	);


const subpax_SFG_f02 =
	translate( [ 356.5880499475629, 79.95575312103882, 84.93672313928086, ],
		rotate( [ -2.8015711249408195, -0.713368694821056, -2.0328958675786275, ],
			   extrudeLinear( {height: 10}, fig_demoSheetFold2_SFG_f02 )
		)
	);


const subpax_SFG_f03 =
	translate( [ 361.6931823621126, 77.1887426856568, 86.78377983451381, ],
		rotate( [ 2.505601436775179, -0.2103438790439557, -0.5727191984948401, ],
			   extrudeLinear( {height: 10}, fig_demoSheetFold2_SFG_f03 )
		)
	);


const subpax_SFG_f04 =
	translate( [ 385.5789955996381, 6.280809970216583, 75.47871682992943, ],
		rotate( [ 0.7176505884067325, 0.9827263374842236, 2.424732299404218, ],
			   extrudeLinear( {height: 10}, fig_demoSheetFold2_SFG_f04 )
		)
	);


const subpax_SFG_fj00 =
	translate( [ 200, 100, 0, ],
		rotate( [ 1.5707963267948966, 0, 0, ],
			   extrudeLinear( {height: 100}, fig_demoSheetFold2_SFG_fj00 )
		)
	);


const subpax_SFG_fj01 =
	translate( [ 206.47047612756302, 100.00000000000003, 0.8518543427732936, ],
		rotate( [ 1.3154153544613625, -0.058254560208720794, 1.351384851712499, ],
			   extrudeLinear( {height: 167}, fig_demoSheetFold2_SFG_fj01 )
		)
	);


const subpax_SFG_fj02 =
	translate( [ 312.29205296473714, 30.025656923156554, 132.56917158535296, ],
		rotate( [ -2.254528246437487, -0.40381198166725474, -0.4158122095646415, ],
			   extrudeLinear( {height: 82}, fig_demoSheetFold2_SFG_fj02 )
		)
	);


const subpax_SFG_fj03 =
	translate( [ 317.39718537928684, 27.25864648777459, 134.4162282805859, ],
		rotate( [ -2.0049846568653997, -0.5212053995231275, -1.1180955130194996, ],
			   extrudeLinear( {height: 79}, fig_demoSheetFold2_SFG_fj03 )
		)
	);

const pax_demoSheetFold2 = union( subpax_SFG_f00, subpax_SFG_f01, subpax_SFG_f02, subpax_SFG_f03, subpax_SFG_f04, subpax_SFG_fj00, subpax_SFG_fj01, subpax_SFG_fj02, subpax_SFG_fj03 );

return pax_demoSheetFold2;
}
module.exports = { main };
