// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_cabane_faceTop_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, -734.0000 ],
	[ 2825.0000, -734.0000 ],
	[ 3211.0000, 977.5000 ],
	[ 2125.0000, 1755.0000 ],
	[ -100.0000, 1755.0000 ],
	[ -1553.0000, 977.5000 ],
	[ 0.0000, -734.0000 ] ] });

face_fig_cabane_faceTop_Fa000 = ctr_face_fig_cabane_faceTop_Fa000_Ctr000;
fig_cabane_faceTop = face_fig_cabane_faceTop_Fa000;
const ctr_face_fig_cabane_faceFaceFront_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 190.0000 ],
	[ 206.5000, 190.0000 ],
	[ -17.4593, 1445.1052 ],
	[ -17.7971, 1447.0615 ],
	[ -18.1131, 1449.0213 ],
	[ -18.4072, 1450.9846 ],
	[ -18.6794, 1452.9511 ],
	[ -18.9297, 1454.9204 ],
	[ -19.1579, 1456.8925 ],
	[ -19.3642, 1458.8669 ],
	[ -19.5484, 1460.8436 ],
	[ -19.7106, 1462.8221 ],
	[ -19.8507, 1464.8024 ],
	[ -19.9687, 1466.7841 ],
	[ -20.0646, 1468.7670 ],
	[ -20.1383, 1470.7508 ],
	[ -20.1900, 1472.7353 ],
	[ -20.2195, 1474.7203 ],
	[ -20.2269, 1476.7055 ],
	[ -20.2121, 1478.6906 ],
	[ -20.1752, 1480.6755 ],
	[ -20.1161, 1482.6598 ],
	[ -20.0349, 1484.6433 ],
	[ -19.9317, 1486.6258 ],
	[ -19.8063, 1488.6071 ],
	[ -19.6588, 1490.5868 ],
	[ -19.4892, 1492.5647 ],
	[ -19.2976, 1494.5407 ],
	[ -19.0840, 1496.5143 ],
	[ -18.8484, 1498.4855 ],
	[ -18.5908, 1500.4539 ],
	[ -18.3113, 1502.4193 ],
	[ -18.0098, 1504.3815 ],
	[ -17.6865, 1506.3402 ],
	[ -17.3414, 1508.2952 ],
	[ -16.9745, 1510.2462 ],
	[ -16.5859, 1512.1930 ],
	[ -16.1755, 1514.1353 ],
	[ -15.7436, 1516.0729 ],
	[ -15.2900, 1518.0056 ],
	[ -14.8150, 1519.9332 ],
	[ -14.3184, 1521.8553 ],
	[ -13.8005, 1523.7717 ],
	[ -13.2612, 1525.6822 ],
	[ -12.7006, 1527.5867 ],
	[ -12.1189, 1529.4847 ],
	[ -11.5160, 1531.3761 ],
	[ -10.8920, 1533.2607 ],
	[ -10.2471, 1535.1382 ],
	[ -9.5812, 1537.0085 ],
	[ -8.8946, 1538.8711 ],
	[ -8.1872, 1540.7260 ],
	[ -7.4592, 1542.5729 ],
	[ -6.7106, 1544.4116 ],
	[ -5.9416, 1546.2418 ],
	[ -5.1522, 1548.0633 ],
	[ -4.3425, 1549.8758 ],
	[ -3.5127, 1551.6793 ],
	[ -2.6628, 1553.4734 ],
	[ -1.7930, 1555.2578 ],
	[ -0.9033, 1557.0325 ],
	[ 0.0062, 1558.7971 ],
	[ 0.9352, 1560.5515 ],
	[ 1.8838, 1562.2955 ],
	[ 2.8517, 1564.0287 ],
	[ 3.8389, 1565.7510 ],
	[ 4.8453, 1567.4622 ],
	[ 5.8707, 1569.1621 ],
	[ 6.9150, 1570.8504 ],
	[ 7.9780, 1572.5270 ],
	[ 9.0597, 1574.1916 ],
	[ 10.1599, 1575.8441 ],
	[ 11.2784, 1577.4842 ],
	[ 12.4152, 1579.1117 ],
	[ 13.5700, 1580.7264 ],
	[ 14.7428, 1582.3282 ],
	[ 15.9334, 1583.9168 ],
	[ 17.1416, 1585.4919 ],
	[ 18.3673, 1587.0536 ],
	[ 19.6104, 1588.6014 ],
	[ 20.8706, 1590.1353 ],
	[ 22.1479, 1591.6551 ],
	[ 23.4420, 1593.1605 ],
	[ 24.7528, 1594.6513 ],
	[ 26.0802, 1596.1275 ],
	[ 27.4240, 1597.5888 ],
	[ 28.7839, 1599.0350 ],
	[ 30.1600, 1600.4659 ],
	[ 489.9375, 2073.2868 ],
	[ 491.3389, 2074.7118 ],
	[ 492.7562, 2076.1210 ],
	[ 494.1892, 2077.5142 ],
	[ 495.6377, 2078.8913 ],
	[ 497.1017, 2080.2519 ],
	[ 498.5808, 2081.5961 ],
	[ 500.0749, 2082.9235 ],
	[ 501.5838, 2084.2341 ],
	[ 503.1074, 2085.5277 ],
	[ 504.6454, 2086.8041 ],
	[ 506.1976, 2088.0631 ],
	[ 507.7638, 2089.3046 ],
	[ 509.3439, 2090.5285 ],
	[ 510.9377, 2091.7345 ],
	[ 512.5448, 2092.9226 ],
	[ 514.1653, 2094.0926 ],
	[ 515.7987, 2095.2443 ],
	[ 517.4450, 2096.3775 ],
	[ 519.1039, 2097.4922 ],
	[ 520.7752, 2098.5883 ],
	[ 522.4587, 2099.6654 ],
	[ 524.1542, 2100.7237 ],
	[ 525.8615, 2101.7628 ],
	[ 527.5803, 2102.7826 ],
	[ 529.3105, 2103.7832 ],
	[ 531.0518, 2104.7642 ],
	[ 532.8040, 2105.7256 ],
	[ 534.5669, 2106.6673 ],
	[ 536.3402, 2107.5891 ],
	[ 538.1238, 2108.4909 ],
	[ 539.9174, 2109.3727 ],
	[ 541.7208, 2110.2343 ],
	[ 543.5338, 2111.0755 ],
	[ 545.3561, 2111.8964 ],
	[ 547.1874, 2112.6967 ],
	[ 549.0277, 2113.4765 ],
	[ 550.8766, 2114.2355 ],
	[ 552.7339, 2114.9737 ],
	[ 554.5994, 2115.6910 ],
	[ 556.4728, 2116.3874 ],
	[ 558.3539, 2117.0626 ],
	[ 560.2425, 2117.7167 ],
	[ 562.1383, 2118.3495 ],
	[ 564.0410, 2118.9610 ],
	[ 565.9506, 2119.5511 ],
	[ 567.8666, 2120.1198 ],
	[ 569.7889, 2120.6668 ],
	[ 571.7172, 2121.1923 ],
	[ 573.6513, 2121.6961 ],
	[ 575.5910, 2122.1781 ],
	[ 577.5359, 2122.6383 ],
	[ 579.4859, 2123.0767 ],
	[ 581.4406, 2123.4931 ],
	[ 583.3999, 2123.8876 ],
	[ 585.3636, 2124.2600 ],
	[ 587.3313, 2124.6104 ],
	[ 589.3027, 2124.9386 ],
	[ 591.2778, 2125.2447 ],
	[ 593.2562, 2125.5286 ],
	[ 595.2376, 2125.7903 ],
	[ 597.2218, 2126.0297 ],
	[ 599.2086, 2126.2468 ],
	[ 601.1978, 2126.4415 ],
	[ 603.1889, 2126.6140 ],
	[ 605.1819, 2126.7640 ],
	[ 607.1765, 2126.8917 ],
	[ 609.1723, 2126.9970 ],
	[ 611.1693, 2127.0799 ],
	[ 613.1670, 2127.1403 ],
	[ 615.1652, 2127.1783 ],
	[ 617.1638, 2127.1939 ],
	[ 619.1624, 2127.1870 ],
	[ 621.1609, 2127.1577 ],
	[ 623.1588, 2127.1059 ],
	[ 625.1561, 2127.0317 ],
	[ 627.1524, 2126.9351 ],
	[ 629.1475, 2126.8161 ],
	[ 631.1411, 2126.6747 ],
	[ 633.1330, 2126.5109 ],
	[ 635.1229, 2126.3248 ],
	[ 637.1107, 2126.1163 ],
	[ 639.0959, 2125.8855 ],
	[ 641.0785, 2125.6325 ],
	[ 643.0581, 2125.3572 ],
	[ 645.0344, 2125.0597 ],
	[ 647.0073, 2124.7400 ],
	[ 648.9765, 2124.3982 ],
	[ 650.9417, 2124.0343 ],
	[ 652.9028, 2123.6483 ],
	[ 654.8593, 2123.2404 ],
	[ 656.8112, 2122.8105 ],
	[ 658.7581, 2122.3587 ],
	[ 660.6998, 2121.8851 ],
	[ 662.6360, 2121.3898 ],
	[ 664.5666, 2120.8727 ],
	[ 666.4913, 2120.3340 ],
	[ 668.4098, 2119.7737 ],
	[ 670.3219, 2119.1918 ],
	[ 672.2273, 2118.5886 ],
	[ 674.1258, 2117.9640 ],
	[ 676.0172, 2117.3181 ],
	[ 677.9012, 2116.6511 ],
	[ 679.7776, 2115.9629 ],
	[ 681.6462, 2115.2537 ],
	[ 683.5067, 2114.5235 ],
	[ 685.3589, 2113.7726 ],
	[ 687.2025, 2113.0008 ],
	[ 689.0373, 2112.2084 ],
	[ 690.8632, 2111.3955 ],
	[ 692.6798, 2110.5621 ],
	[ 694.4869, 2109.7084 ],
	[ 696.2843, 2108.8344 ],
	[ 698.0718, 2107.9403 ],
	[ 699.8491, 2107.0262 ],
	[ 701.6161, 2106.0922 ],
	[ 703.3725, 2105.1384 ],
	[ 705.1180, 2104.1650 ],
	[ 706.8525, 2103.1720 ],
	[ 708.5758, 2102.1596 ],
	[ 710.2875, 2101.1279 ],
	[ 711.9876, 2100.0771 ],
	[ 713.6758, 2099.0072 ],
	[ 715.3518, 2097.9184 ],
	[ 717.0156, 2096.8109 ],
	[ 718.6667, 2095.6848 ],
	[ 720.3052, 2094.5403 ],
	[ 721.9307, 2093.3774 ],
	[ 723.5430, 2092.1963 ],
	[ 725.1419, 2090.9972 ],
	[ 726.7273, 2089.7802 ],
	[ 728.2990, 2088.5455 ],
	[ 729.8566, 2087.2932 ],
	[ 731.4001, 2086.0235 ],
	[ 732.9293, 2084.7366 ],
	[ 734.4439, 2083.4325 ],
	[ 735.9438, 2082.1116 ],
	[ 737.4287, 2080.7739 ],
	[ 738.8986, 2079.4196 ],
	[ 740.3531, 2078.0488 ],
	[ 741.7921, 2076.6619 ],
	[ 743.2155, 2075.2588 ],
	[ 744.6231, 2073.8399 ],
	[ 746.0146, 2072.4053 ],
	[ 747.3899, 2070.9551 ],
	[ 748.7489, 2069.4896 ],
	[ 750.0913, 2068.0089 ],
	[ 751.4170, 2066.5132 ],
	[ 752.7258, 2065.0027 ],
	[ 754.0176, 2063.4777 ],
	[ 755.2922, 2061.9382 ],
	[ 756.5494, 2060.3845 ],
	[ 757.7891, 2058.8168 ],
	[ 759.0111, 2057.2353 ],
	[ 760.2153, 2055.6402 ],
	[ 761.4015, 2054.0316 ],
	[ 762.5695, 2052.4098 ],
	[ 763.7193, 2050.7750 ],
	[ 764.8507, 2049.1274 ],
	[ 765.9634, 2047.4672 ],
	[ 767.0575, 2045.7946 ],
	[ 768.1327, 2044.1098 ],
	[ 769.1889, 2042.4131 ],
	[ 770.2260, 2040.7046 ],
	[ 771.2439, 2038.9846 ],
	[ 772.2424, 2037.2533 ],
	[ 773.2214, 2035.5108 ],
	[ 774.1807, 2033.7575 ],
	[ 775.1203, 2031.9935 ],
	[ 776.0401, 2030.2191 ],
	[ 776.9399, 2028.4344 ],
	[ 777.8195, 2026.6398 ],
	[ 778.6790, 2024.8354 ],
	[ 779.5181, 2023.0214 ],
	[ 1321.6876, 833.5681 ],
	[ 1322.5008, 831.7573 ],
	[ 1323.2938, 829.9376 ],
	[ 1324.0664, 828.1091 ],
	[ 1324.8186, 826.2722 ],
	[ 1325.5502, 824.4269 ],
	[ 1326.2613, 822.5737 ],
	[ 1326.9516, 820.7126 ],
	[ 1327.6211, 818.8439 ],
	[ 1328.2697, 816.9679 ],
	[ 1328.8974, 815.0847 ],
	[ 1329.5041, 813.1947 ],
	[ 1330.0896, 811.2980 ],
	[ 1330.6540, 809.3950 ],
	[ 1331.1970, 807.4857 ],
	[ 1331.7188, 805.5705 ],
	[ 1332.2192, 803.6496 ],
	[ 1332.6981, 801.7233 ],
	[ 1333.1555, 799.7917 ],
	[ 1333.5914, 797.8551 ],
	[ 1334.0056, 795.9138 ],
	[ 1334.3981, 793.9680 ],
	[ 1334.7689, 792.0180 ],
	[ 1335.1180, 790.0639 ],
	[ 1335.4452, 788.1061 ],
	[ 1335.7506, 786.1447 ],
	[ 1336.0341, 784.1801 ],
	[ 1336.2957, 782.2124 ],
	[ 1336.5353, 780.2419 ],
	[ 1336.7529, 778.2689 ],
	[ 1336.9485, 776.2936 ],
	[ 1337.1221, 774.3162 ],
	[ 1337.2736, 772.3370 ],
	[ 1337.4030, 770.3562 ],
	[ 1337.5103, 768.3741 ],
	[ 1337.5956, 766.3909 ],
	[ 1337.6587, 764.4069 ],
	[ 1337.6996, 762.4224 ],
	[ 1337.7185, 760.4375 ],
	[ 1337.7152, 758.4525 ],
	[ 1337.6897, 756.4676 ],
	[ 1337.6422, 754.4832 ],
	[ 1337.5725, 752.4995 ],
	[ 1337.4807, 750.5166 ],
	[ 1337.3667, 748.5349 ],
	[ 1337.2307, 746.5545 ],
	[ 1337.0726, 744.5758 ],
	[ 1336.8925, 742.5990 ],
	[ 1336.6903, 740.6244 ],
	[ 1336.4661, 738.6521 ],
	[ 1336.2200, 736.6824 ],
	[ 1335.9519, 734.7156 ],
	[ 1335.6618, 732.7519 ],
	[ 1335.3499, 730.7916 ],
	[ 1335.0162, 728.8348 ],
	[ 1334.6606, 726.8819 ],
	[ 1334.2833, 724.9331 ],
	[ 1333.8843, 722.9887 ],
	[ 1333.4636, 721.0487 ],
	[ 1333.0214, 719.1137 ],
	[ 1332.5575, 717.1836 ],
	[ 1332.0722, 715.2589 ],
	[ 1331.5655, 713.3396 ],
	[ 1331.0373, 711.4262 ],
	[ 1330.4879, 709.5188 ],
	[ 1329.9172, 707.6176 ],
	[ 1329.3254, 705.7228 ],
	[ 1328.7125, 703.8349 ],
	[ 1328.0785, 701.9538 ],
	[ 1327.4236, 700.0800 ],
	[ 1326.7479, 698.2135 ],
	[ 1326.0514, 696.3547 ],
	[ 1325.3342, 694.5038 ],
	[ 1324.5964, 692.6610 ],
	[ 1323.8381, 690.8266 ],
	[ 1323.0594, 689.0007 ],
	[ 1322.2604, 687.1836 ],
	[ 1321.4412, 685.3756 ],
	[ 1320.6018, 683.5768 ],
	[ 1319.7425, 681.7874 ],
	[ 1318.8632, 680.0078 ],
	[ 1317.9642, 678.2381 ],
	[ 1066.5000, 190.0000 ],
	[ 1401.0000, 190.0000 ],
	[ 1545.0000, 1989.4643 ],
	[ 977.5000, 2620.1009 ],
	[ 977.5000, 2626.4810 ],
	[ -295.0000, 1839.1147 ],
	[ 0.0000, 190.0000 ] ] });

face_fig_cabane_faceFaceFront_Fa000 = ctr_face_fig_cabane_faceFaceFront_Fa000_Ctr000;
fig_cabane_faceFaceFront = face_fig_cabane_faceFaceFront_Fa000;
const ctr_face_fig_cabane_faceFaceBack_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 190.0000 ],
	[ 1401.0000, 190.0000 ],
	[ 1545.0000, 1989.4643 ],
	[ 977.5000, 2620.1009 ],
	[ 977.5000, 2626.4810 ],
	[ -295.0000, 1839.1147 ],
	[ 0.0000, 190.0000 ] ] });

face_fig_cabane_faceFaceBack_Fa000 = ctr_face_fig_cabane_faceFaceBack_Fa000_Ctr000;
const ctr_face_fig_cabane_faceFaceBack_Fa001_Ctr000 = polygon({ points: [ [ 155.1618, 334.0000 ],
	[ 709.8910, 334.0000 ],
	[ 711.8754, 334.0328 ],
	[ 713.8576, 334.1313 ],
	[ 715.8354, 334.2952 ],
	[ 717.8068, 334.5245 ],
	[ 719.7695, 334.8188 ],
	[ 721.7214, 335.1779 ],
	[ 723.6603, 335.6013 ],
	[ 725.5842, 336.0886 ],
	[ 727.4909, 336.6393 ],
	[ 729.3783, 337.2528 ],
	[ 731.2445, 337.9283 ],
	[ 733.0872, 338.6652 ],
	[ 734.9046, 339.4627 ],
	[ 736.6946, 340.3198 ],
	[ 738.4553, 341.2356 ],
	[ 740.1848, 342.2092 ],
	[ 741.8811, 343.2394 ],
	[ 743.5424, 344.3252 ],
	[ 745.1668, 345.4653 ],
	[ 746.7527, 346.6585 ],
	[ 748.2983, 347.9035 ],
	[ 749.8018, 349.1990 ],
	[ 751.2617, 350.5435 ],
	[ 752.6763, 351.9355 ],
	[ 754.0440, 353.3735 ],
	[ 755.3635, 354.8560 ],
	[ 756.6332, 356.3813 ],
	[ 757.8518, 357.9478 ],
	[ 759.0179, 359.5537 ],
	[ 760.1303, 361.1973 ],
	[ 761.1877, 362.8768 ],
	[ 762.1890, 364.5904 ],
	[ 763.1330, 366.3361 ],
	[ 764.0188, 368.1121 ],
	[ 764.8454, 369.9164 ],
	[ 765.6118, 371.7471 ],
	[ 766.3173, 373.6021 ],
	[ 766.9611, 375.4794 ],
	[ 1256.0182, 1882.4794 ],
	[ 1256.5993, 1884.3761 ],
	[ 1257.1173, 1886.2910 ],
	[ 1257.5717, 1888.2219 ],
	[ 1257.9621, 1890.1668 ],
	[ 1258.2880, 1892.1236 ],
	[ 1258.5490, 1894.0900 ],
	[ 1258.7448, 1896.0640 ],
	[ 1258.8753, 1898.0434 ],
	[ 1258.9403, 1900.0261 ],
	[ 1258.9397, 1902.0098 ],
	[ 1258.8735, 1903.9924 ],
	[ 1258.7419, 1905.9717 ],
	[ 1258.5448, 1907.9456 ],
	[ 1258.2827, 1909.9119 ],
	[ 1257.9556, 1911.8684 ],
	[ 1257.5641, 1913.8131 ],
	[ 1257.1085, 1915.7438 ],
	[ 1256.5893, 1917.6583 ],
	[ 1256.0071, 1919.5546 ],
	[ 1255.3626, 1921.4307 ],
	[ 1254.6564, 1923.2844 ],
	[ 1253.8893, 1925.1138 ],
	[ 1253.0621, 1926.9168 ],
	[ 1252.1758, 1928.6915 ],
	[ 1251.2313, 1930.4359 ],
	[ 1250.2297, 1932.1482 ],
	[ 1249.1720, 1933.8264 ],
	[ 1248.0594, 1935.4687 ],
	[ 1246.8931, 1937.0733 ],
	[ 1245.6744, 1938.6385 ],
	[ 1244.4047, 1940.1626 ],
	[ 1243.0852, 1941.6438 ],
	[ 1241.7175, 1943.0807 ],
	[ 1240.3031, 1944.4715 ],
	[ 1238.8435, 1945.8148 ],
	[ 1237.3402, 1947.1091 ],
	[ 1235.7950, 1948.3531 ],
	[ 1234.2095, 1949.5452 ],
	[ 1232.5855, 1950.6843 ],
	[ 1230.9247, 1951.7691 ],
	[ 1229.2289, 1952.7984 ],
	[ 1227.5001, 1953.7711 ],
	[ 1225.7400, 1954.6861 ],
	[ 1223.9506, 1955.5424 ],
	[ 1222.1340, 1956.3391 ],
	[ 1220.2919, 1957.0753 ],
	[ 1218.4266, 1957.7503 ],
	[ 1216.5399, 1958.3631 ],
	[ 1214.6341, 1958.9133 ],
	[ 1212.7111, 1959.4002 ],
	[ 1210.7730, 1959.8232 ],
	[ 1208.8220, 1960.1820 ],
	[ 1206.8602, 1960.4760 ],
	[ 1204.8898, 1960.7051 ],
	[ 1202.9129, 1960.8689 ],
	[ 1200.9316, 1960.9672 ],
	[ 1198.9482, 1961.0000 ],
	[ 336.7058, 1961.0000 ],
	[ 334.7276, 1960.9674 ],
	[ 332.7516, 1960.8696 ],
	[ 330.7799, 1960.7067 ],
	[ 328.8147, 1960.4788 ],
	[ 326.8580, 1960.1863 ],
	[ 324.9120, 1959.8295 ],
	[ 322.9789, 1959.4087 ],
	[ 321.0606, 1958.9243 ],
	[ 319.1594, 1958.3770 ],
	[ 317.2773, 1957.7674 ],
	[ 315.4163, 1957.0960 ],
	[ 313.5784, 1956.3636 ],
	[ 311.7657, 1955.5710 ],
	[ 309.9801, 1954.7191 ],
	[ 308.2236, 1953.8087 ],
	[ 306.4980, 1952.8410 ],
	[ 304.8052, 1951.8169 ],
	[ 303.1472, 1950.7375 ],
	[ 301.5256, 1949.6041 ],
	[ 299.9423, 1948.4178 ],
	[ 298.3990, 1947.1800 ],
	[ 296.8973, 1945.8919 ],
	[ 295.4389, 1944.5551 ],
	[ 294.0253, 1943.1708 ],
	[ 292.6582, 1941.7408 ],
	[ 291.3390, 1940.2664 ],
	[ 290.0690, 1938.7494 ],
	[ 288.8498, 1937.1913 ],
	[ 287.6826, 1935.5938 ],
	[ 286.5688, 1933.9588 ],
	[ 285.5094, 1932.2879 ],
	[ 284.5057, 1930.5830 ],
	[ 283.5587, 1928.8459 ],
	[ 282.6696, 1927.0785 ],
	[ 281.8392, 1925.2828 ],
	[ 281.0684, 1923.4607 ],
	[ 280.3581, 1921.6142 ],
	[ 279.7091, 1919.7452 ],
	[ 279.1221, 1917.8559 ],
	[ 278.5977, 1915.9483 ],
	[ 278.1365, 1914.0244 ],
	[ 277.7389, 1912.0863 ],
	[ 277.4054, 1910.1362 ],
	[ 277.1365, 1908.1761 ],
	[ 95.5925, 401.1761 ],
	[ 95.3874, 399.1978 ],
	[ 95.2480, 397.2137 ],
	[ 95.1744, 395.2262 ],
	[ 95.1667, 393.2372 ],
	[ 95.2249, 391.2491 ],
	[ 95.3490, 389.2640 ],
	[ 95.5389, 387.2842 ],
	[ 95.7942, 385.3117 ],
	[ 96.1148, 383.3487 ],
	[ 96.5003, 381.3975 ],
	[ 96.9502, 379.4601 ],
	[ 97.4641, 377.5387 ],
	[ 98.0414, 375.6354 ],
	[ 98.6815, 373.7522 ],
	[ 99.3836, 371.8913 ],
	[ 100.1471, 370.0547 ],
	[ 100.9710, 368.2444 ],
	[ 101.8544, 366.4625 ],
	[ 102.7964, 364.7107 ],
	[ 103.7959, 362.9912 ],
	[ 104.8519, 361.3057 ],
	[ 105.9632, 359.6562 ],
	[ 107.1286, 358.0444 ],
	[ 108.3467, 356.4721 ],
	[ 109.6163, 354.9410 ],
	[ 110.9359, 353.4529 ],
	[ 112.3041, 352.0093 ],
	[ 113.7194, 350.6119 ],
	[ 115.1803, 349.2622 ],
	[ 116.6851, 347.9616 ],
	[ 118.2321, 346.7116 ],
	[ 119.8198, 345.5135 ],
	[ 121.4463, 344.3688 ],
	[ 123.1098, 343.2785 ],
	[ 124.8085, 342.2441 ],
	[ 126.5407, 341.2664 ],
	[ 128.3042, 340.3468 ],
	[ 130.0973, 339.4861 ],
	[ 131.9179, 338.6853 ],
	[ 133.7641, 337.9452 ],
	[ 135.6337, 337.2668 ],
	[ 137.5249, 336.6507 ],
	[ 139.4354, 336.0977 ],
	[ 141.3632, 335.6082 ],
	[ 143.3061, 335.1830 ],
	[ 145.2621, 334.8223 ],
	[ 147.2290, 334.5267 ],
	[ 149.2045, 334.2965 ],
	[ 151.1867, 334.1318 ],
	[ 153.1732, 334.0330 ],
	[ 155.1618, 334.0000 ] ] });

face_fig_cabane_faceFaceBack_Fa001 = ctr_face_fig_cabane_faceFaceBack_Fa001_Ctr000;
fig_cabane_faceFaceBack = union( face_fig_cabane_faceFaceBack_Fa000, face_fig_cabane_faceFaceBack_Fa001 );
const ctr_face_fig_cabane_faceFaceRoof_Fa000_Ctr000 = polygon({ points: [ [ 977.5000, 2650.0000 ],
	[ -734.0000, 1591.0000 ],
	[ -723.4765, 1573.9925 ],
	[ 977.5000, 2626.4810 ],
	[ 977.5000, 2620.1009 ],
	[ 1740.1333, 1772.6217 ],
	[ 1755.0000, 1786.0000 ],
	[ 977.5000, 2650.0000 ] ] });

face_fig_cabane_faceFaceRoof_Fa000 = ctr_face_fig_cabane_faceFaceRoof_Fa000_Ctr000;
fig_cabane_faceFaceRoof = face_fig_cabane_faceFaceRoof_Fa000;
const ctr_face_fig_cabane_faceFaceSide_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 190.0000 ],
	[ 20.3175, 190.0000 ],
	[ -276.7073, 1850.4334 ],
	[ -295.0000, 1839.1147 ],
	[ 0.0000, 190.0000 ] ] });

face_fig_cabane_faceFaceSide_Fa000 = ctr_face_fig_cabane_faceFaceSide_Fa000_Ctr000;
const ctr_face_fig_cabane_faceFaceSide_Fa001_Ctr000 = polygon({ points: [ [ 1401.0000, 190.0000 ],
	[ 1545.0000, 1989.4643 ],
	[ 1526.5746, 2009.9396 ],
	[ 1380.9361, 190.0000 ],
	[ 1401.0000, 190.0000 ] ] });

face_fig_cabane_faceFaceSide_Fa001 = ctr_face_fig_cabane_faceFaceSide_Fa001_Ctr000;
fig_cabane_faceFaceSide = union( face_fig_cabane_faceFaceSide_Fa000, face_fig_cabane_faceFaceSide_Fa001 );
const ctr_face_fig_cabane_faceSide_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 190.0000 ],
	[ 1958.0000, 190.0000 ],
	[ 1958.0000, 1839.1147 ],
	[ 0.0000, 1839.1147 ],
	[ 0.0000, 190.0000 ] ] });

face_fig_cabane_faceSide_Fa000 = ctr_face_fig_cabane_faceSide_Fa000_Ctr000;
const ctr_face_fig_cabane_faceSide_Fa001_Ctr000 = polygon({ points: [ [ -1553.0000, 2650.0000 ],
	[ 0.0000, 1591.0000 ],
	[ 2825.0000, 1591.0000 ],
	[ 3211.0000, 2650.0000 ],
	[ -1553.0000, 2650.0000 ] ] });

face_fig_cabane_faceSide_Fa001 = ctr_face_fig_cabane_faceSide_Fa001_Ctr000;
fig_cabane_faceSide = union( face_fig_cabane_faceSide_Fa000, face_fig_cabane_faceSide_Fa001 );
const ctr_face_fig_cabane_plancher_facePlancherTop_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 1958.0000, 0.0000 ],
	[ 1958.0000, 174.9500 ],
	[ 0.0000, 174.9500 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherTop_Fa000 = ctr_face_fig_cabane_plancher_facePlancherTop_Fa000_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherTop_Fa001_Ctr000 = polygon({ points: [ [ 0.0000, 175.1500 ],
	[ 1958.0000, 175.1500 ],
	[ 1958.0000, 350.1000 ],
	[ 0.0000, 350.1000 ],
	[ 0.0000, 175.1500 ] ] });

face_fig_cabane_plancher_facePlancherTop_Fa001 = ctr_face_fig_cabane_plancher_facePlancherTop_Fa001_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherTop_Fa002_Ctr000 = polygon({ points: [ [ 0.0000, 350.3000 ],
	[ 1958.0000, 350.3000 ],
	[ 1958.0000, 525.2500 ],
	[ 0.0000, 525.2500 ],
	[ 0.0000, 350.3000 ] ] });

face_fig_cabane_plancher_facePlancherTop_Fa002 = ctr_face_fig_cabane_plancher_facePlancherTop_Fa002_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherTop_Fa003_Ctr000 = polygon({ points: [ [ 0.0000, 525.4500 ],
	[ 1958.0000, 525.4500 ],
	[ 1958.0000, 700.4000 ],
	[ 0.0000, 700.4000 ],
	[ 0.0000, 525.4500 ] ] });

face_fig_cabane_plancher_facePlancherTop_Fa003 = ctr_face_fig_cabane_plancher_facePlancherTop_Fa003_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherTop_Fa004_Ctr000 = polygon({ points: [ [ 0.0000, 700.6000 ],
	[ 1958.0000, 700.6000 ],
	[ 1958.0000, 875.5500 ],
	[ 0.0000, 875.5500 ],
	[ 0.0000, 700.6000 ] ] });

face_fig_cabane_plancher_facePlancherTop_Fa004 = ctr_face_fig_cabane_plancher_facePlancherTop_Fa004_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherTop_Fa005_Ctr000 = polygon({ points: [ [ 0.0000, 875.7500 ],
	[ 1958.0000, 875.7500 ],
	[ 1958.0000, 1050.7000 ],
	[ 0.0000, 1050.7000 ],
	[ 0.0000, 875.7500 ] ] });

face_fig_cabane_plancher_facePlancherTop_Fa005 = ctr_face_fig_cabane_plancher_facePlancherTop_Fa005_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherTop_Fa006_Ctr000 = polygon({ points: [ [ 0.0000, 1050.9000 ],
	[ 1958.0000, 1050.9000 ],
	[ 1958.0000, 1225.8500 ],
	[ 0.0000, 1225.8500 ],
	[ 0.0000, 1050.9000 ] ] });

face_fig_cabane_plancher_facePlancherTop_Fa006 = ctr_face_fig_cabane_plancher_facePlancherTop_Fa006_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherTop_Fa007_Ctr000 = polygon({ points: [ [ 0.0000, 1226.0500 ],
	[ 1958.0000, 1226.0500 ],
	[ 1958.0000, 1401.0000 ],
	[ 0.0000, 1401.0000 ],
	[ 0.0000, 1226.0500 ] ] });

face_fig_cabane_plancher_facePlancherTop_Fa007 = ctr_face_fig_cabane_plancher_facePlancherTop_Fa007_Ctr000;
fig_cabane_plancher_facePlancherTop = union( face_fig_cabane_plancher_facePlancherTop_Fa000, face_fig_cabane_plancher_facePlancherTop_Fa001, face_fig_cabane_plancher_facePlancherTop_Fa002, face_fig_cabane_plancher_facePlancherTop_Fa003, face_fig_cabane_plancher_facePlancherTop_Fa004, face_fig_cabane_plancher_facePlancherTop_Fa005, face_fig_cabane_plancher_facePlancherTop_Fa006, face_fig_cabane_plancher_facePlancherTop_Fa007 );
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 150.4308, 0.0000 ],
	[ 150.4308, 1401.0000 ],
	[ 0.0000, 1401.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa000 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa000_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa001_Ctr000 = polygon({ points: [ [ 150.6308, 0.0000 ],
	[ 301.0615, 0.0000 ],
	[ 301.0615, 1401.0000 ],
	[ 150.6308, 1401.0000 ],
	[ 150.6308, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa001 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa001_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa002_Ctr000 = polygon({ points: [ [ 301.2615, 0.0000 ],
	[ 451.6923, 0.0000 ],
	[ 451.6923, 1401.0000 ],
	[ 301.2615, 1401.0000 ],
	[ 301.2615, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa002 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa002_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa003_Ctr000 = polygon({ points: [ [ 451.8923, 0.0000 ],
	[ 602.3231, 0.0000 ],
	[ 602.3231, 1401.0000 ],
	[ 451.8923, 1401.0000 ],
	[ 451.8923, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa003 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa003_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa004_Ctr000 = polygon({ points: [ [ 602.5231, 0.0000 ],
	[ 752.9538, 0.0000 ],
	[ 752.9538, 1401.0000 ],
	[ 602.5231, 1401.0000 ],
	[ 602.5231, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa004 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa004_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa005_Ctr000 = polygon({ points: [ [ 753.1538, 0.0000 ],
	[ 903.5846, 0.0000 ],
	[ 903.5846, 1401.0000 ],
	[ 753.1538, 1401.0000 ],
	[ 753.1538, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa005 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa005_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa006_Ctr000 = polygon({ points: [ [ 903.7846, 0.0000 ],
	[ 1054.2154, 0.0000 ],
	[ 1054.2154, 1401.0000 ],
	[ 903.7846, 1401.0000 ],
	[ 903.7846, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa006 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa006_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa007_Ctr000 = polygon({ points: [ [ 1054.4154, 0.0000 ],
	[ 1204.8462, 0.0000 ],
	[ 1204.8462, 1401.0000 ],
	[ 1054.4154, 1401.0000 ],
	[ 1054.4154, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa007 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa007_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa008_Ctr000 = polygon({ points: [ [ 1205.0462, 0.0000 ],
	[ 1355.4769, 0.0000 ],
	[ 1355.4769, 1401.0000 ],
	[ 1205.0462, 1401.0000 ],
	[ 1205.0462, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa008 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa008_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa009_Ctr000 = polygon({ points: [ [ 1355.6769, 0.0000 ],
	[ 1506.1077, 0.0000 ],
	[ 1506.1077, 1401.0000 ],
	[ 1355.6769, 1401.0000 ],
	[ 1355.6769, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa009 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa009_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa010_Ctr000 = polygon({ points: [ [ 1506.3077, 0.0000 ],
	[ 1656.7385, 0.0000 ],
	[ 1656.7385, 1401.0000 ],
	[ 1506.3077, 1401.0000 ],
	[ 1506.3077, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa010 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa010_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa011_Ctr000 = polygon({ points: [ [ 1656.9385, 0.0000 ],
	[ 1807.3692, 0.0000 ],
	[ 1807.3692, 1401.0000 ],
	[ 1656.9385, 1401.0000 ],
	[ 1656.9385, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa011 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa011_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa012_Ctr000 = polygon({ points: [ [ 1807.5692, 0.0000 ],
	[ 1958.0000, 0.0000 ],
	[ 1958.0000, 1401.0000 ],
	[ 1807.5692, 1401.0000 ],
	[ 1807.5692, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa012 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa012_Ctr000;
fig_cabane_plancher_facePlancherBottom = union( face_fig_cabane_plancher_facePlancherBottom_Fa000, face_fig_cabane_plancher_facePlancherBottom_Fa001, face_fig_cabane_plancher_facePlancherBottom_Fa002, face_fig_cabane_plancher_facePlancherBottom_Fa003, face_fig_cabane_plancher_facePlancherBottom_Fa004, face_fig_cabane_plancher_facePlancherBottom_Fa005, face_fig_cabane_plancher_facePlancherBottom_Fa006, face_fig_cabane_plancher_facePlancherBottom_Fa007, face_fig_cabane_plancher_facePlancherBottom_Fa008, face_fig_cabane_plancher_facePlancherBottom_Fa009, face_fig_cabane_plancher_facePlancherBottom_Fa010, face_fig_cabane_plancher_facePlancherBottom_Fa011, face_fig_cabane_plancher_facePlancherBottom_Fa012 );
const ctr_face_fig_cabane_plancher_faceBeam_Fa000_Ctr000 = polygon({ points: [ [ 70.0500, 150.0000 ],
	[ 140.1000, 150.0000 ],
	[ 140.1000, 85.6213 ],
	[ 139.1000, 79.9500 ],
	[ 70.0500, 79.9500 ],
	[ 70.0500, 150.0000 ] ] });

face_fig_cabane_plancher_faceBeam_Fa000 = ctr_face_fig_cabane_plancher_faceBeam_Fa000_Ctr000;
const ctr_face_fig_cabane_plancher_faceBeam_Fa001_Ctr000 = polygon({ points: [ [ 1330.9500, 150.0000 ],
	[ 1260.9000, 150.0000 ],
	[ 1260.9000, 85.6213 ],
	[ 1261.9000, 79.9500 ],
	[ 1330.9500, 79.9500 ],
	[ 1330.9500, 150.0000 ] ] });

face_fig_cabane_plancher_faceBeam_Fa001 = ctr_face_fig_cabane_plancher_faceBeam_Fa001_Ctr000;
fig_cabane_plancher_faceBeam = union( face_fig_cabane_plancher_faceBeam_Fa000, face_fig_cabane_plancher_faceBeam_Fa001 );
const ctr_face_fig_cabane_plancher_faceLeg_Fa000_Ctr000 = polygon({ points: [ [ 222.5823, 150.0000 ],
	[ 151.4517, 150.0000 ],
	[ 125.0027, 0.0000 ],
	[ 196.1333, 0.0000 ],
	[ 222.5823, 150.0000 ] ] });

face_fig_cabane_plancher_faceLeg_Fa000 = ctr_face_fig_cabane_plancher_faceLeg_Fa000_Ctr000;
const ctr_face_fig_cabane_plancher_faceLeg_Fa001_Ctr000 = polygon({ points: [ [ 1178.4177, 150.0000 ],
	[ 1249.5483, 150.0000 ],
	[ 1275.9973, 0.0000 ],
	[ 1204.8667, 0.0000 ],
	[ 1178.4177, 150.0000 ] ] });

face_fig_cabane_plancher_faceLeg_Fa001 = ctr_face_fig_cabane_plancher_faceLeg_Fa001_Ctr000;
fig_cabane_plancher_faceLeg = union( face_fig_cabane_plancher_faceLeg_Fa000, face_fig_cabane_plancher_faceLeg_Fa001 );
const ctr_face_fig_cabane_plancher_faceButtress_Fa000_Ctr000 = polygon({ points: [ [ 222.5823, 150.0000 ],
	[ 1178.4177, 150.0000 ],
	[ 1190.7694, 79.9500 ],
	[ 210.2306, 79.9500 ],
	[ 222.5823, 150.0000 ] ] });

face_fig_cabane_plancher_faceButtress_Fa000 = ctr_face_fig_cabane_plancher_faceButtress_Fa000_Ctr000;
fig_cabane_plancher_faceButtress = face_fig_cabane_plancher_faceButtress_Fa000;
const ctr_face_fig_cabane_plancher_faceSide_Fa000_Ctr000 = polygon({ points: [ [ 140.1000, 0.0000 ],
	[ 210.1500, 0.0000 ],
	[ 210.1500, 150.0000 ],
	[ 140.1000, 150.0000 ],
	[ 140.1000, 0.0000 ] ] });

face_fig_cabane_plancher_faceSide_Fa000 = ctr_face_fig_cabane_plancher_faceSide_Fa000_Ctr000;
const ctr_face_fig_cabane_plancher_faceSide_Fa001_Ctr000 = polygon({ points: [ [ 1747.8500, 0.0000 ],
	[ 1817.9000, 0.0000 ],
	[ 1817.9000, 150.0000 ],
	[ 1747.8500, 150.0000 ],
	[ 1747.8500, 0.0000 ] ] });

face_fig_cabane_plancher_faceSide_Fa001 = ctr_face_fig_cabane_plancher_faceSide_Fa001_Ctr000;
fig_cabane_plancher_faceSide = union( face_fig_cabane_plancher_faceSide_Fa000, face_fig_cabane_plancher_faceSide_Fa001 );

const subpax_cabane_plancher_plancherTop =
	translate( [ 0, 0, 170, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 20}, fig_cabane_plancher_facePlancherTop )
		)
	);


const subpax_cabane_plancher_plancherBottom =
	translate( [ 0, 0, 150, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 20}, fig_cabane_plancher_facePlancherBottom )
		)
	);


const subpax_cabane_plancher_beam =
	translate( [ 1958, 1401.0000000000002, 0, ],
		rotate( [ 1.5707963267948966, 0, -1.5707963267948966, ],
			   extrudeLinear( {height: 1958}, fig_cabane_plancher_faceBeam )
		)
	);


const subpax_cabane_plancher_leg1 =
	translate( [ 210.14999999999998, 1401, 0, ],
		rotate( [ 1.5707963267948966, 0, -1.5707963267948966, ],
			   extrudeLinear( {height: 70.05}, fig_cabane_plancher_faceLeg )
		)
	);


const subpax_cabane_plancher_leg2 =
	translate( [ 1817.9, 1401, 0, ],
		rotate( [ 1.5707963267948966, 0, -1.5707963267948966, ],
			   extrudeLinear( {height: 70.05}, fig_cabane_plancher_faceLeg )
		)
	);


const subpax_cabane_plancher_buttress1 =
	translate( [ 210.14999999999998, 1401, 0, ],
		rotate( [ 1.5707963267948966, 0, -1.5707963267948966, ],
			   extrudeLinear( {height: 70.05}, fig_cabane_plancher_faceButtress )
		)
	);


const subpax_cabane_plancher_buttress2 =
	translate( [ 1817.9, 1401, 0, ],
		rotate( [ 1.5707963267948966, 0, -1.5707963267948966, ],
			   extrudeLinear( {height: 70.05}, fig_cabane_plancher_faceButtress )
		)
	);

const pax_cabane_plancher = union( subpax_cabane_plancher_plancherTop, subpax_cabane_plancher_plancherBottom, subpax_cabane_plancher_beam, subpax_cabane_plancher_leg1, subpax_cabane_plancher_leg2, subpax_cabane_plancher_buttress1, subpax_cabane_plancher_buttress2 );

const inpax_cabane_plancher =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0, ],
			   pax_cabane_plancher
		)
	);

const subpax_cabane_roofTop =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 2650}, fig_cabane_faceTop )
		)
	);


const subpax_cabane_roofMax =
	translate( [ -1553, 0, 0, ],
		rotate( [ 1.5707963267948966, 0, 1.5707963267948966, ],
			   extrudeLinear( {height: 4764}, fig_cabane_faceFaceRoof )
		)
	);


const subpax_cabane_Wfront =
	translate( [ 1938, 0, 0, ],
		rotate( [ 1.5707963267948966, 0, 1.5707963267948966, ],
			   extrudeLinear( {height: 20}, fig_cabane_faceFaceFront )
		)
	);


const subpax_cabane_Wback =
	translate( [ 0, 0, 0, ],
		rotate( [ 1.5707963267948966, 0, 1.5707963267948966, ],
			   extrudeLinear( {height: 20}, fig_cabane_faceFaceBack )
		)
	);


const subpax_cabane_Wside =
	translate( [ 0, 0, 0, ],
		rotate( [ 1.5707963267948966, 0, 1.5707963267948966, ],
			   extrudeLinear( {height: 1958}, fig_cabane_faceFaceSide )
		)
	);

const ipax_cabane_roof = intersect( subpax_cabane_roofMax, subpax_cabane_roofTop );
const pax_cabane = union( inpax_cabane_plancher, ipax_cabane_roof, subpax_cabane_Wfront, subpax_cabane_Wback, subpax_cabane_Wside );

return pax_cabane;
}
module.exports = { main };
