// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_demoSheetFold2_SFG_pattern_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 200.0000, 0.0000 ],
	[ 220.9440, 0.0000 ],
	[ 307.5465, 50.0000 ],
	[ 318.0185, 68.1380 ],
	[ 338.9624, 68.1380 ],
	[ 425.5650, 118.1380 ],
	[ 436.0369, 136.2760 ],
	[ 486.0369, 222.8785 ],
	[ 399.4344, 272.8785 ],
	[ 349.4344, 186.2760 ],
	[ 338.9624, 168.1380 ],
	[ 318.0185, 168.1380 ],
	[ 231.4159, 118.1380 ],
	[ 220.9440, 100.0000 ],
	[ 200.0000, 100.0000 ],
	[ 0.0000, 100.0000 ],
	[ 0.0000, 0.0000 ] ] });

const ctr_face_fig_demoSheetFold2_SFG_pattern_Fa000_Ctr001 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 200.0000, 0.0000 ],
	[ 220.9440, 0.0000 ],
	[ 307.5465, 50.0000 ],
	[ 318.0185, 68.1380 ],
	[ 338.9624, 68.1380 ],
	[ 425.5650, 118.1380 ],
	[ 436.0369, 136.2760 ],
	[ 486.0369, 222.8785 ],
	[ 399.4344, 272.8785 ],
	[ 349.4344, 186.2760 ],
	[ 338.9624, 168.1380 ],
	[ 318.0185, 168.1380 ],
	[ 231.4159, 118.1380 ],
	[ 220.9440, 100.0000 ],
	[ 200.0000, 100.0000 ],
	[ 0.0000, 100.0000 ],
	[ 0.0000, 0.0000 ] ] });

const ctr_face_fig_demoSheetFold2_SFG_pattern_Fa000_Ctr002 = polygon({ points: [ [ 219.9440, 49.0000 ],
	[ 220.1390, 49.0192 ],
	[ 220.3266, 49.0761 ],
	[ 220.4995, 49.1685 ],
	[ 220.6511, 49.2929 ],
	[ 220.7754, 49.4444 ],
	[ 220.8678, 49.6173 ],
	[ 220.9247, 49.8049 ],
	[ 220.9440, 50.0000 ],
	[ 220.9247, 50.1951 ],
	[ 220.8678, 50.3827 ],
	[ 220.7754, 50.5556 ],
	[ 220.6511, 50.7071 ],
	[ 220.4995, 50.8315 ],
	[ 220.3266, 50.9239 ],
	[ 220.1390, 50.9808 ],
	[ 219.9440, 51.0000 ],
	[ 201.0000, 51.0000 ],
	[ 200.8049, 50.9808 ],
	[ 200.6173, 50.9239 ],
	[ 200.4444, 50.8315 ],
	[ 200.2929, 50.7071 ],
	[ 200.1685, 50.5556 ],
	[ 200.0761, 50.3827 ],
	[ 200.0192, 50.1951 ],
	[ 200.0000, 50.0000 ],
	[ 200.0192, 49.8049 ],
	[ 200.0761, 49.6173 ],
	[ 200.1685, 49.4444 ],
	[ 200.2929, 49.2929 ],
	[ 200.4444, 49.1685 ],
	[ 200.6173, 49.0761 ],
	[ 200.8049, 49.0192 ],
	[ 201.0000, 49.0000 ],
	[ 219.9440, 49.0000 ] ] });

const ctr_face_fig_demoSheetFold2_SFG_pattern_Fa000_Ctr003 = polygon({ points: [ [ 263.8792, 76.3660 ],
	[ 263.7983, 76.1875 ],
	[ 263.7538, 75.9966 ],
	[ 263.7474, 75.8006 ],
	[ 263.7793, 75.6072 ],
	[ 263.8483, 75.4237 ],
	[ 263.9519, 75.2573 ],
	[ 264.0859, 75.1142 ],
	[ 264.2452, 75.0000 ],
	[ 264.4238, 74.9191 ],
	[ 264.6147, 74.8746 ],
	[ 264.8106, 74.8682 ],
	[ 265.0040, 74.9001 ],
	[ 265.1875, 74.9692 ],
	[ 265.3540, 75.0727 ],
	[ 265.4971, 75.2067 ],
	[ 265.6112, 75.3660 ],
	[ 275.0832, 91.7720 ],
	[ 275.1641, 91.9505 ],
	[ 275.2086, 92.1414 ],
	[ 275.2151, 92.3374 ],
	[ 275.1831, 92.5308 ],
	[ 275.1141, 92.7143 ],
	[ 275.0106, 92.8807 ],
	[ 274.8765, 93.0238 ],
	[ 274.7172, 93.1380 ],
	[ 274.5386, 93.2189 ],
	[ 274.3477, 93.2634 ],
	[ 274.1518, 93.2698 ],
	[ 273.9584, 93.2379 ],
	[ 273.7749, 93.1688 ],
	[ 273.6084, 93.0653 ],
	[ 273.4654, 92.9313 ],
	[ 273.3512, 92.7720 ],
	[ 263.8792, 76.3660 ] ] });

const ctr_face_fig_demoSheetFold2_SFG_pattern_Fa000_Ctr004 = polygon({ points: [ [ 337.9624, 117.1380 ],
	[ 338.1575, 117.1572 ],
	[ 338.3451, 117.2141 ],
	[ 338.5180, 117.3065 ],
	[ 338.6695, 117.4309 ],
	[ 338.7939, 117.5824 ],
	[ 338.8863, 117.7553 ],
	[ 338.9432, 117.9429 ],
	[ 338.9624, 118.1380 ],
	[ 338.9432, 118.3331 ],
	[ 338.8863, 118.5207 ],
	[ 338.7939, 118.6936 ],
	[ 338.6695, 118.8451 ],
	[ 338.5180, 118.9695 ],
	[ 338.3451, 119.0619 ],
	[ 338.1575, 119.1188 ],
	[ 337.9624, 119.1380 ],
	[ 319.0185, 119.1380 ],
	[ 318.8234, 119.1188 ],
	[ 318.6358, 119.0619 ],
	[ 318.4629, 118.9695 ],
	[ 318.3114, 118.8451 ],
	[ 318.1870, 118.6936 ],
	[ 318.0946, 118.5207 ],
	[ 318.0377, 118.3331 ],
	[ 318.0185, 118.1380 ],
	[ 318.0377, 117.9429 ],
	[ 318.0946, 117.7553 ],
	[ 318.1870, 117.5824 ],
	[ 318.3114, 117.4309 ],
	[ 318.4629, 117.3065 ],
	[ 318.6358, 117.2141 ],
	[ 318.8234, 117.1572 ],
	[ 319.0185, 117.1380 ],
	[ 337.9624, 117.1380 ] ] });

const ctr_face_fig_demoSheetFold2_SFG_pattern_Fa000_Ctr005 = polygon({ points: [ [ 393.1017, 159.9100 ],
	[ 393.1826, 160.0885 ],
	[ 393.2271, 160.2794 ],
	[ 393.2335, 160.4754 ],
	[ 393.2016, 160.6688 ],
	[ 393.1325, 160.8523 ],
	[ 393.0290, 161.0187 ],
	[ 392.8950, 161.1618 ],
	[ 392.7357, 161.2760 ],
	[ 392.5571, 161.3569 ],
	[ 392.3662, 161.4014 ],
	[ 392.1703, 161.4078 ],
	[ 391.9768, 161.3759 ],
	[ 391.7934, 161.3068 ],
	[ 391.6269, 161.2033 ],
	[ 391.4838, 161.0693 ],
	[ 391.3696, 160.9100 ],
	[ 381.8977, 144.5040 ],
	[ 381.8205, 144.3364 ],
	[ 381.7755, 144.1574 ],
	[ 381.7642, 143.9732 ],
	[ 381.7868, 143.7901 ],
	[ 381.8428, 143.6142 ],
	[ 381.9301, 143.4517 ],
	[ 382.0458, 143.3079 ],
	[ 382.1859, 143.1878 ],
	[ 382.3457, 143.0956 ],
	[ 382.5198, 143.0342 ],
	[ 382.7021, 143.0059 ],
	[ 382.8866, 143.0116 ],
	[ 383.0668, 143.0511 ],
	[ 383.2368, 143.1230 ],
	[ 383.3906, 143.2249 ],
	[ 383.5231, 143.3534 ],
	[ 383.6297, 143.5040 ],
	[ 393.1017, 159.9100 ] ] });

face_fig_demoSheetFold2_SFG_pattern_Fa000 = subtract( ctr_face_fig_demoSheetFold2_SFG_pattern_Fa000_Ctr000, ctr_face_fig_demoSheetFold2_SFG_pattern_Fa000_Ctr001, ctr_face_fig_demoSheetFold2_SFG_pattern_Fa000_Ctr002, ctr_face_fig_demoSheetFold2_SFG_pattern_Fa000_Ctr003, ctr_face_fig_demoSheetFold2_SFG_pattern_Fa000_Ctr004, ctr_face_fig_demoSheetFold2_SFG_pattern_Fa000_Ctr005 );
fig_demoSheetFold2_SFG_pattern = face_fig_demoSheetFold2_SFG_pattern_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_profiles_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 200.0000, 0.0000 ],
	[ 200.0000, 10.0000 ],
	[ 0.0000, 10.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_profiles_Fa000 = ctr_face_fig_demoSheetFold2_SFG_profiles_Fa000_Ctr000;
const ctr_face_fig_demoSheetFold2_SFG_profiles_Fa001_Ctr000 = polygon({ points: [ [ 200.0000, 0.0000 ],
	[ 201.8683, 0.0699 ],
	[ 203.7261, 0.2792 ],
	[ 205.5630, 0.6268 ],
	[ 207.3689, 1.1107 ],
	[ 209.1335, 1.7282 ],
	[ 210.8471, 2.4758 ],
	[ 212.5000, 3.3494 ],
	[ 214.0830, 4.3440 ],
	[ 215.5872, 5.4542 ],
	[ 217.0043, 6.6737 ],
	[ 218.3263, 7.9957 ],
	[ 219.5458, 9.4128 ],
	[ 220.6560, 10.9170 ],
	[ 221.6506, 12.5000 ],
	[ 212.9904, 17.5000 ],
	[ 211.9003, 15.8686 ],
	[ 210.6066, 14.3934 ],
	[ 209.1314, 13.0997 ],
	[ 207.5000, 12.0096 ],
	[ 205.7403, 11.1418 ],
	[ 203.8823, 10.5111 ],
	[ 201.9579, 10.1283 ],
	[ 200.0000, 10.0000 ],
	[ 200.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_profiles_Fa001 = ctr_face_fig_demoSheetFold2_SFG_profiles_Fa001_Ctr000;
const ctr_face_fig_demoSheetFold2_SFG_profiles_Fa002_Ctr000 = polygon({ points: [ [ 221.6506, 12.5000 ],
	[ 271.6506, 99.1025 ],
	[ 262.9904, 104.1025 ],
	[ 212.9904, 17.5000 ],
	[ 221.6506, 12.5000 ] ] });

face_fig_demoSheetFold2_SFG_profiles_Fa002 = ctr_face_fig_demoSheetFold2_SFG_profiles_Fa002_Ctr000;
const ctr_face_fig_demoSheetFold2_SFG_profiles_Fa003_Ctr000 = polygon({ points: [ [ 271.6506, 99.1025 ],
	[ 272.5242, 100.7554 ],
	[ 273.2718, 102.4690 ],
	[ 273.8893, 104.2337 ],
	[ 274.3732, 106.0395 ],
	[ 274.7208, 107.8765 ],
	[ 274.9301, 109.7343 ],
	[ 275.0000, 111.6025 ],
	[ 274.9301, 113.4708 ],
	[ 274.7208, 115.3286 ],
	[ 274.3732, 117.1656 ],
	[ 273.8893, 118.9714 ],
	[ 273.2718, 120.7361 ],
	[ 272.5242, 122.4496 ],
	[ 271.6506, 124.1025 ],
	[ 262.9904, 119.1025 ],
	[ 263.8582, 117.3428 ],
	[ 264.4889, 115.4848 ],
	[ 264.8717, 113.5604 ],
	[ 265.0000, 111.6025 ],
	[ 264.8717, 109.6446 ],
	[ 264.4889, 107.7203 ],
	[ 263.8582, 105.8623 ],
	[ 262.9904, 104.1025 ],
	[ 271.6506, 99.1025 ] ] });

face_fig_demoSheetFold2_SFG_profiles_Fa003 = ctr_face_fig_demoSheetFold2_SFG_profiles_Fa003_Ctr000;
const ctr_face_fig_demoSheetFold2_SFG_profiles_Fa004_Ctr000 = polygon({ points: [ [ 271.6506, 124.1025 ],
	[ 271.1506, 124.9686 ],
	[ 262.4904, 119.9686 ],
	[ 262.9904, 119.1025 ],
	[ 271.6506, 124.1025 ] ] });

face_fig_demoSheetFold2_SFG_profiles_Fa004 = ctr_face_fig_demoSheetFold2_SFG_profiles_Fa004_Ctr000;
const ctr_face_fig_demoSheetFold2_SFG_profiles_Fa005_Ctr000 = polygon({ points: [ [ 271.1506, 124.9686 ],
	[ 270.1560, 126.5516 ],
	[ 269.0458, 128.0558 ],
	[ 267.8263, 129.4729 ],
	[ 266.5043, 130.7949 ],
	[ 265.0872, 132.0144 ],
	[ 263.5830, 133.1245 ],
	[ 262.0000, 134.1192 ],
	[ 260.3471, 134.9928 ],
	[ 258.6335, 135.7404 ],
	[ 256.8689, 136.3579 ],
	[ 255.0630, 136.8418 ],
	[ 253.2261, 137.1893 ],
	[ 251.3683, 137.3987 ],
	[ 249.5000, 137.4686 ],
	[ 249.5000, 127.4686 ],
	[ 251.4579, 127.3402 ],
	[ 253.3823, 126.9575 ],
	[ 255.2403, 126.3268 ],
	[ 257.0000, 125.4589 ],
	[ 258.6314, 124.3689 ],
	[ 260.1066, 123.0752 ],
	[ 261.4003, 121.6000 ],
	[ 262.4904, 119.9686 ],
	[ 271.1506, 124.9686 ] ] });

face_fig_demoSheetFold2_SFG_profiles_Fa005 = ctr_face_fig_demoSheetFold2_SFG_profiles_Fa005_Ctr000;
const ctr_face_fig_demoSheetFold2_SFG_profiles_Fa006_Ctr000 = polygon({ points: [ [ 249.5000, 137.4686 ],
	[ 149.5000, 137.4686 ],
	[ 149.5000, 127.4686 ],
	[ 249.5000, 127.4686 ],
	[ 249.5000, 137.4686 ] ] });

face_fig_demoSheetFold2_SFG_profiles_Fa006 = ctr_face_fig_demoSheetFold2_SFG_profiles_Fa006_Ctr000;
const ctr_face_fig_demoSheetFold2_SFG_profiles_Fa007_Ctr000 = polygon({ points: [ [ 149.5000, 137.4686 ],
	[ 147.6317, 137.3987 ],
	[ 145.7739, 137.1893 ],
	[ 143.9370, 136.8418 ],
	[ 142.1311, 136.3579 ],
	[ 140.3665, 135.7404 ],
	[ 138.6529, 134.9928 ],
	[ 137.0000, 134.1192 ],
	[ 135.4170, 133.1245 ],
	[ 133.9128, 132.0144 ],
	[ 132.4957, 130.7949 ],
	[ 131.1737, 129.4729 ],
	[ 129.9542, 128.0558 ],
	[ 128.8440, 126.5516 ],
	[ 127.8494, 124.9686 ],
	[ 136.5096, 119.9686 ],
	[ 137.5997, 121.6000 ],
	[ 138.8934, 123.0752 ],
	[ 140.3686, 124.3689 ],
	[ 142.0000, 125.4589 ],
	[ 143.7597, 126.3268 ],
	[ 145.6177, 126.9575 ],
	[ 147.5421, 127.3402 ],
	[ 149.5000, 127.4686 ],
	[ 149.5000, 137.4686 ] ] });

face_fig_demoSheetFold2_SFG_profiles_Fa007 = ctr_face_fig_demoSheetFold2_SFG_profiles_Fa007_Ctr000;
const ctr_face_fig_demoSheetFold2_SFG_profiles_Fa008_Ctr000 = polygon({ points: [ [ 127.8494, 124.9686 ],
	[ 77.8494, 38.3660 ],
	[ 86.5096, 33.3660 ],
	[ 136.5096, 119.9686 ],
	[ 127.8494, 124.9686 ] ] });

face_fig_demoSheetFold2_SFG_profiles_Fa008 = ctr_face_fig_demoSheetFold2_SFG_profiles_Fa008_Ctr000;
const ctr_face_fig_demoSheetFold2_SFG_profiles_Fa009_Ctr000 = polygon({ points: [ [ 0.0000, 400.0000 ],
	[ 200.0000, 400.0000 ],
	[ 200.0000, 410.0000 ],
	[ 0.0000, 410.0000 ],
	[ 0.0000, 400.0000 ] ] });

face_fig_demoSheetFold2_SFG_profiles_Fa009 = ctr_face_fig_demoSheetFold2_SFG_profiles_Fa009_Ctr000;
const ctr_face_fig_demoSheetFold2_SFG_profiles_Fa010_Ctr000 = polygon({ points: [ [ 200.0000, 400.0000 ],
	[ 201.8683, 400.0699 ],
	[ 203.7261, 400.2792 ],
	[ 205.5630, 400.6268 ],
	[ 207.3689, 401.1107 ],
	[ 209.1335, 401.7282 ],
	[ 210.8471, 402.4758 ],
	[ 212.5000, 403.3494 ],
	[ 214.0830, 404.3440 ],
	[ 215.5872, 405.4542 ],
	[ 217.0043, 406.6737 ],
	[ 218.3263, 407.9957 ],
	[ 219.5458, 409.4128 ],
	[ 220.6560, 410.9170 ],
	[ 221.6506, 412.5000 ],
	[ 212.9904, 417.5000 ],
	[ 211.9003, 415.8686 ],
	[ 210.6066, 414.3934 ],
	[ 209.1314, 413.0997 ],
	[ 207.5000, 412.0096 ],
	[ 205.7403, 411.1418 ],
	[ 203.8823, 410.5111 ],
	[ 201.9579, 410.1283 ],
	[ 200.0000, 410.0000 ],
	[ 200.0000, 400.0000 ] ] });

face_fig_demoSheetFold2_SFG_profiles_Fa010 = ctr_face_fig_demoSheetFold2_SFG_profiles_Fa010_Ctr000;
const ctr_face_fig_demoSheetFold2_SFG_profiles_Fa011_Ctr000 = polygon({ points: [ [ 221.6506, 412.5000 ],
	[ 222.1506, 413.3660 ],
	[ 213.4904, 418.3660 ],
	[ 212.9904, 417.5000 ],
	[ 221.6506, 412.5000 ] ] });

face_fig_demoSheetFold2_SFG_profiles_Fa011 = ctr_face_fig_demoSheetFold2_SFG_profiles_Fa011_Ctr000;
const ctr_face_fig_demoSheetFold2_SFG_profiles_Fa012_Ctr000 = polygon({ points: [ [ 222.1506, 413.3660 ],
	[ 223.0242, 415.0189 ],
	[ 223.7718, 416.7325 ],
	[ 224.3893, 418.4971 ],
	[ 224.8732, 420.3030 ],
	[ 225.2208, 422.1400 ],
	[ 225.4301, 423.9978 ],
	[ 225.5000, 425.8660 ],
	[ 225.4301, 427.7343 ],
	[ 225.2208, 429.5921 ],
	[ 224.8732, 431.4290 ],
	[ 224.3893, 433.2349 ],
	[ 223.7718, 434.9996 ],
	[ 223.0242, 436.7131 ],
	[ 222.1506, 438.3660 ],
	[ 213.4904, 433.3660 ],
	[ 214.3582, 431.6063 ],
	[ 214.9889, 429.7483 ],
	[ 215.3717, 427.8239 ],
	[ 215.5000, 425.8660 ],
	[ 215.3717, 423.9081 ],
	[ 214.9889, 421.9837 ],
	[ 214.3582, 420.1258 ],
	[ 213.4904, 418.3660 ],
	[ 222.1506, 413.3660 ] ] });

face_fig_demoSheetFold2_SFG_profiles_Fa012 = ctr_face_fig_demoSheetFold2_SFG_profiles_Fa012_Ctr000;
const ctr_face_fig_demoSheetFold2_SFG_profiles_Fa013_Ctr000 = polygon({ points: [ [ 222.1506, 438.3660 ],
	[ 172.1506, 524.9686 ],
	[ 163.4904, 519.9686 ],
	[ 213.4904, 433.3660 ],
	[ 222.1506, 438.3660 ] ] });

face_fig_demoSheetFold2_SFG_profiles_Fa013 = ctr_face_fig_demoSheetFold2_SFG_profiles_Fa013_Ctr000;
const ctr_face_fig_demoSheetFold2_SFG_profiles_Fa014_Ctr000 = polygon({ points: [ [ 172.1506, 524.9686 ],
	[ 171.1560, 526.5516 ],
	[ 170.0458, 528.0558 ],
	[ 168.8263, 529.4729 ],
	[ 167.5043, 530.7949 ],
	[ 166.0872, 532.0144 ],
	[ 164.5830, 533.1245 ],
	[ 163.0000, 534.1192 ],
	[ 161.3471, 534.9928 ],
	[ 159.6335, 535.7404 ],
	[ 157.8689, 536.3579 ],
	[ 156.0630, 536.8418 ],
	[ 154.2261, 537.1893 ],
	[ 152.3683, 537.3987 ],
	[ 150.5000, 537.4686 ],
	[ 150.5000, 527.4686 ],
	[ 152.4579, 527.3402 ],
	[ 154.3823, 526.9575 ],
	[ 156.2403, 526.3268 ],
	[ 158.0000, 525.4589 ],
	[ 159.6314, 524.3689 ],
	[ 161.1066, 523.0752 ],
	[ 162.4003, 521.6000 ],
	[ 163.4904, 519.9686 ],
	[ 172.1506, 524.9686 ] ] });

face_fig_demoSheetFold2_SFG_profiles_Fa014 = ctr_face_fig_demoSheetFold2_SFG_profiles_Fa014_Ctr000;
const ctr_face_fig_demoSheetFold2_SFG_profiles_Fa015_Ctr000 = polygon({ points: [ [ 150.5000, 537.4686 ],
	[ 149.5000, 537.4686 ],
	[ 149.5000, 527.4686 ],
	[ 150.5000, 527.4686 ],
	[ 150.5000, 537.4686 ] ] });

face_fig_demoSheetFold2_SFG_profiles_Fa015 = ctr_face_fig_demoSheetFold2_SFG_profiles_Fa015_Ctr000;
const ctr_face_fig_demoSheetFold2_SFG_profiles_Fa016_Ctr000 = polygon({ points: [ [ 149.5000, 537.4686 ],
	[ 147.6317, 537.3987 ],
	[ 145.7739, 537.1893 ],
	[ 143.9370, 536.8418 ],
	[ 142.1311, 536.3579 ],
	[ 140.3665, 535.7404 ],
	[ 138.6529, 534.9928 ],
	[ 137.0000, 534.1192 ],
	[ 135.4170, 533.1245 ],
	[ 133.9128, 532.0144 ],
	[ 132.4957, 530.7949 ],
	[ 131.1737, 529.4729 ],
	[ 129.9542, 528.0558 ],
	[ 128.8440, 526.5516 ],
	[ 127.8494, 524.9686 ],
	[ 136.5096, 519.9686 ],
	[ 137.5997, 521.6000 ],
	[ 138.8934, 523.0752 ],
	[ 140.3686, 524.3689 ],
	[ 142.0000, 525.4589 ],
	[ 143.7597, 526.3268 ],
	[ 145.6177, 526.9575 ],
	[ 147.5421, 527.3402 ],
	[ 149.5000, 527.4686 ],
	[ 149.5000, 537.4686 ] ] });

face_fig_demoSheetFold2_SFG_profiles_Fa016 = ctr_face_fig_demoSheetFold2_SFG_profiles_Fa016_Ctr000;
const ctr_face_fig_demoSheetFold2_SFG_profiles_Fa017_Ctr000 = polygon({ points: [ [ 127.8494, 524.9686 ],
	[ 77.8494, 438.3660 ],
	[ 86.5096, 433.3660 ],
	[ 136.5096, 519.9686 ],
	[ 127.8494, 524.9686 ] ] });

face_fig_demoSheetFold2_SFG_profiles_Fa017 = ctr_face_fig_demoSheetFold2_SFG_profiles_Fa017_Ctr000;
fig_demoSheetFold2_SFG_profiles = union( face_fig_demoSheetFold2_SFG_profiles_Fa000, face_fig_demoSheetFold2_SFG_profiles_Fa001, face_fig_demoSheetFold2_SFG_profiles_Fa002, face_fig_demoSheetFold2_SFG_profiles_Fa003, face_fig_demoSheetFold2_SFG_profiles_Fa004, face_fig_demoSheetFold2_SFG_profiles_Fa005, face_fig_demoSheetFold2_SFG_profiles_Fa006, face_fig_demoSheetFold2_SFG_profiles_Fa007, face_fig_demoSheetFold2_SFG_profiles_Fa008, face_fig_demoSheetFold2_SFG_profiles_Fa009, face_fig_demoSheetFold2_SFG_profiles_Fa010, face_fig_demoSheetFold2_SFG_profiles_Fa011, face_fig_demoSheetFold2_SFG_profiles_Fa012, face_fig_demoSheetFold2_SFG_profiles_Fa013, face_fig_demoSheetFold2_SFG_profiles_Fa014, face_fig_demoSheetFold2_SFG_profiles_Fa015, face_fig_demoSheetFold2_SFG_profiles_Fa016, face_fig_demoSheetFold2_SFG_profiles_Fa017 );
const ctr_face_fig_demoSheetFold2_SFG_f00_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 200.0000, 0.0000 ],
	[ 200.0000, 100.0000 ],
	[ 0.0000, 100.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_f00_Fa000 = ctr_face_fig_demoSheetFold2_SFG_f00_Fa000_Ctr000;
fig_demoSheetFold2_SFG_f00 = face_fig_demoSheetFold2_SFG_f00_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_f01_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 100.0000 ],
	[ 0.0000, 0.0000 ],
	[ 86.6025, 50.0000 ],
	[ 0.0000, 100.0000 ] ] });

face_fig_demoSheetFold2_SFG_f01_Fa000 = ctr_face_fig_demoSheetFold2_SFG_f01_Fa000_Ctr000;
fig_demoSheetFold2_SFG_f01 = face_fig_demoSheetFold2_SFG_f01_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_f02_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 100.0000 ],
	[ -86.6025, 50.0000 ],
	[ 0.0000, 0.0000 ],
	[ 0.0000, 100.0000 ] ] });

face_fig_demoSheetFold2_SFG_f02_Fa000 = ctr_face_fig_demoSheetFold2_SFG_f02_Fa000_Ctr000;
fig_demoSheetFold2_SFG_f02 = face_fig_demoSheetFold2_SFG_f02_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_f03_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 100.0000 ],
	[ 0.0000, 0.0000 ],
	[ 86.6025, 50.0000 ],
	[ 0.0000, 100.0000 ] ] });

face_fig_demoSheetFold2_SFG_f03_Fa000 = ctr_face_fig_demoSheetFold2_SFG_f03_Fa000_Ctr000;
fig_demoSheetFold2_SFG_f03 = face_fig_demoSheetFold2_SFG_f03_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_f04_Fa000_Ctr000 = polygon({ points: [ [ -0.0000, 0.0000 ],
	[ 100.0000, 0.0000 ],
	[ 100.0000, 100.0000 ],
	[ -0.0000, 100.0000 ],
	[ -0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_f04_Fa000 = ctr_face_fig_demoSheetFold2_SFG_f04_Fa000_Ctr000;
fig_demoSheetFold2_SFG_f04 = face_fig_demoSheetFold2_SFG_f04_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_fj00_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 1.8683, 0.0699 ],
	[ 3.7261, 0.2792 ],
	[ 5.5630, 0.6268 ],
	[ 7.3689, 1.1107 ],
	[ 9.1335, 1.7282 ],
	[ 10.8471, 2.4758 ],
	[ 12.5000, 3.3494 ],
	[ 14.0830, 4.3440 ],
	[ 15.5872, 5.4542 ],
	[ 17.0043, 6.6737 ],
	[ 18.3263, 7.9957 ],
	[ 19.5458, 9.4128 ],
	[ 20.6560, 10.9170 ],
	[ 21.6506, 12.5000 ],
	[ 12.9904, 17.5000 ],
	[ 11.9003, 15.8686 ],
	[ 10.6066, 14.3934 ],
	[ 9.1314, 13.0997 ],
	[ 7.5000, 12.0096 ],
	[ 5.7403, 11.1418 ],
	[ 3.8823, 10.5111 ],
	[ 1.9579, 10.1283 ],
	[ -0.0000, 10.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_fj00_Fa000 = ctr_face_fig_demoSheetFold2_SFG_fj00_Fa000_Ctr000;
fig_demoSheetFold2_SFG_fj00 = face_fig_demoSheetFold2_SFG_fj00_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_fj01_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 1.8683, 0.0699 ],
	[ 3.7261, 0.2792 ],
	[ 5.5630, 0.6268 ],
	[ 7.3689, 1.1107 ],
	[ 9.1335, 1.7282 ],
	[ 10.8471, 2.4758 ],
	[ 12.5000, 3.3494 ],
	[ 14.0830, 4.3440 ],
	[ 15.5872, 5.4542 ],
	[ 17.0043, 6.6737 ],
	[ 18.3263, 7.9957 ],
	[ 19.5458, 9.4128 ],
	[ 20.6560, 10.9170 ],
	[ 21.6506, 12.5000 ],
	[ 12.9904, 17.5000 ],
	[ 11.9003, 15.8686 ],
	[ 10.6066, 14.3934 ],
	[ 9.1314, 13.0997 ],
	[ 7.5000, 12.0096 ],
	[ 5.7403, 11.1418 ],
	[ 3.8823, 10.5111 ],
	[ 1.9579, 10.1283 ],
	[ -0.0000, 10.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_fj01_Fa000 = ctr_face_fig_demoSheetFold2_SFG_fj01_Fa000_Ctr000;
fig_demoSheetFold2_SFG_fj01 = face_fig_demoSheetFold2_SFG_fj01_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_fj02_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 1.8683, 0.0699 ],
	[ 3.7261, 0.2792 ],
	[ 5.5630, 0.6268 ],
	[ 7.3689, 1.1107 ],
	[ 9.1335, 1.7282 ],
	[ 10.8471, 2.4758 ],
	[ 12.5000, 3.3494 ],
	[ 14.0830, 4.3440 ],
	[ 15.5872, 5.4542 ],
	[ 17.0043, 6.6737 ],
	[ 18.3263, 7.9957 ],
	[ 19.5458, 9.4128 ],
	[ 20.6560, 10.9170 ],
	[ 21.6506, 12.5000 ],
	[ 12.9904, 17.5000 ],
	[ 11.9003, 15.8686 ],
	[ 10.6066, 14.3934 ],
	[ 9.1314, 13.0997 ],
	[ 7.5000, 12.0096 ],
	[ 5.7403, 11.1418 ],
	[ 3.8823, 10.5111 ],
	[ 1.9579, 10.1283 ],
	[ -0.0000, 10.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_fj02_Fa000 = ctr_face_fig_demoSheetFold2_SFG_fj02_Fa000_Ctr000;
fig_demoSheetFold2_SFG_fj02 = face_fig_demoSheetFold2_SFG_fj02_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_fj03_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 1.8683, 0.0699 ],
	[ 3.7261, 0.2792 ],
	[ 5.5630, 0.6268 ],
	[ 7.3689, 1.1107 ],
	[ 9.1335, 1.7282 ],
	[ 10.8471, 2.4758 ],
	[ 12.5000, 3.3494 ],
	[ 14.0830, 4.3440 ],
	[ 15.5872, 5.4542 ],
	[ 17.0043, 6.6737 ],
	[ 18.3263, 7.9957 ],
	[ 19.5458, 9.4128 ],
	[ 20.6560, 10.9170 ],
	[ 21.6506, 12.5000 ],
	[ 12.9904, 17.5000 ],
	[ 11.9003, 15.8686 ],
	[ 10.6066, 14.3934 ],
	[ 9.1314, 13.0997 ],
	[ 7.5000, 12.0096 ],
	[ 5.7403, 11.1418 ],
	[ 3.8823, 10.5111 ],
	[ 1.9579, 10.1283 ],
	[ -0.0000, 10.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_fj03_Fa000 = ctr_face_fig_demoSheetFold2_SFG_fj03_Fa000_Ctr000;
fig_demoSheetFold2_SFG_fj03 = face_fig_demoSheetFold2_SFG_fj03_Fa000;

const subpax_SFG_f00 =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 10}, fig_demoSheetFold2_SFG_f00 )
		)
	);


const subpax_SFG_f01 =
	translate( [ 221.65063509461098, -1.3257190484061335e-15, 12.5, ],
		rotate( [ -1.0605752387249065e-16, -1.0471975511965976, 6.123233995736764e-17, ],
			   extrudeLinear( {height: 10}, fig_demoSheetFold2_SFG_f01 )
		)
	);


const subpax_SFG_f02 =
	translate( [ 216.2379763209582, 118.75000000000001, 28.124999999999986, ],
		rotate( [ 1.7359450042095237, 0.7069517278872178, -0.6058911188392467, ],
			   extrudeLinear( {height: 10}, fig_demoSheetFold2_SFG_f02 )
		)
	);


const subpax_SFG_f03 =
	translate( [ 252.77342304311424, 54.68749999999998, 122.65625, ],
		rotate( [ 2.937574673997245, -0.3885923754020987, -2.182238833502109, ],
			   extrudeLinear( {height: 10}, fig_demoSheetFold2_SFG_f03 )
		)
	);


const subpax_SFG_f04 =
	translate( [ 144.18195639670608, 21.484375000000046, 161.1328125, ],
		rotate( [ -2.8416454970928515, 0.6547035431023785, -3.039059376929411, ],
			   extrudeLinear( {height: 10}, fig_demoSheetFold2_SFG_f04 )
		)
	);


const subpax_SFG_fj00 =
	translate( [ 200, 100, 0, ],
		rotate( [ 1.5707963267948966, 0, 0, ],
			   extrudeLinear( {height: 100}, fig_demoSheetFold2_SFG_fj00 )
		)
	);


const subpax_SFG_fj01 =
	translate( [ 221.65063509461095, 100.00000000000001, 12.499999999999979, ],
		rotate( [ 0.5880026035475677, -0.4478323969289326, 1.2897614252920828, ],
			   extrudeLinear( {height: 100.00000000000001}, fig_demoSheetFold2_SFG_fj01 )
		)
	);


const subpax_SFG_fj02 =
	translate( [ 183.7620236790418, 131.25, 121.87499999999997, ],
		rotate( [ -2.5535900500422257, -1.3434971907867974, -1.289761425292083, ],
			   extrudeLinear( {height: 100}, fig_demoSheetFold2_SFG_fj02 )
		)
	);


const subpax_SFG_fj03 =
	translate( [ 176.99620021197586, 117.18750000000007, 141.40625, ],
		rotate( [ -1.3177206746302943, -0.35951771175635555, 2.967240339518106, ],
			   extrudeLinear( {height: 100.00000000000001}, fig_demoSheetFold2_SFG_fj03 )
		)
	);

const pax_demoSheetFold2 = union( subpax_SFG_f00, subpax_SFG_f01, subpax_SFG_f02, subpax_SFG_f03, subpax_SFG_f04, subpax_SFG_fj00, subpax_SFG_fj01, subpax_SFG_fj02, subpax_SFG_fj03 );

return pax_demoSheetFold2;
}
module.exports = { main };
