// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 200.0000, 0.0000 ],
	[ 200.0000, 100.0000 ],
	[ 0.0000, 100.0000 ],
	[ 0.0000, 0.0000 ] ] });

const ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr001 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 100.0000, 0.0000 ],
	[ 96.1618, 103.1209 ],
	[ 0.0000, 0.0000 ] ] });

const ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr002 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 82.0000, 0.0000 ],
	[ 31.7181, 137.3862 ],
	[ 0.0000, 0.0000 ] ] });

const ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr003 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 82.0000, 0.0000 ],
	[ 65.4940, 44.1762 ],
	[ 0.0000, 0.0000 ] ] });

const ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr004 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 100.0000, 0.0000 ],
	[ 100.0000, 79.0000 ],
	[ 0.0000, 79.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_facePattern_Fa000 = subtract( ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr000, ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr001, ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr002, ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr003, ctr_face_fig_demoSheetFold2_facePattern_Fa000_Ctr004 );
fig_demoSheetFold2_facePattern = face_fig_demoSheetFold2_facePattern_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_f00_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 200.0000, 0.0000 ],
	[ 200.0000, 100.0000 ],
	[ 0.0000, 100.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_f00_Fa000 = ctr_face_fig_demoSheetFold2_SFG_f00_Fa000_Ctr000;
fig_demoSheetFold2_SFG_f00 = face_fig_demoSheetFold2_SFG_f00_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_f01_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 100.0000 ],
	[ 0.0000, 0.0000 ],
	[ 103.1209, 3.8382 ],
	[ 0.0000, 100.0000 ] ] });

face_fig_demoSheetFold2_SFG_f01_Fa000 = ctr_face_fig_demoSheetFold2_SFG_f01_Fa000_Ctr000;
fig_demoSheetFold2_SFG_f01 = face_fig_demoSheetFold2_SFG_f01_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_f02_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 79.8983, 18.4460 ],
	[ 0.0000, 141.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_f02_Fa000 = ctr_face_fig_demoSheetFold2_SFG_f02_Fa000_Ctr000;
fig_demoSheetFold2_SFG_f02 = face_fig_demoSheetFold2_SFG_f02_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_f03_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 82.0000 ],
	[ 0.0000, 0.0000 ],
	[ 44.1762, 16.5060 ],
	[ 0.0000, 82.0000 ] ] });

face_fig_demoSheetFold2_SFG_f03_Fa000 = ctr_face_fig_demoSheetFold2_SFG_f03_Fa000_Ctr000;
fig_demoSheetFold2_SFG_f03 = face_fig_demoSheetFold2_SFG_f03_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_f04_Fa000_Ctr000 = polygon({ points: [ [ -0.0000, 0.0000 ],
	[ 100.0000, 0.0000 ],
	[ 100.0000, 79.0000 ],
	[ -0.0000, 79.0000 ],
	[ -0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_f04_Fa000 = ctr_face_fig_demoSheetFold2_SFG_f04_Fa000_Ctr000;
fig_demoSheetFold2_SFG_f04 = face_fig_demoSheetFold2_SFG_f04_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_fj00_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 1.9520, 0.0763 ],
	[ 3.8921, 0.3048 ],
	[ 5.8085, 0.6841 ],
	[ 7.6893, 1.2119 ],
	[ 9.5233, 1.8849 ],
	[ 11.2990, 2.6991 ],
	[ 13.0058, 3.6494 ],
	[ 14.6332, 4.7301 ],
	[ 16.1712, 5.9345 ],
	[ 17.6105, 7.2554 ],
	[ 18.9422, 8.6846 ],
	[ 20.1583, 10.2134 ],
	[ 21.2513, 11.8326 ],
	[ 22.2146, 13.5321 ],
	[ 23.0422, 15.3016 ],
	[ 23.7291, 17.1304 ],
	[ 24.2711, 19.0072 ],
	[ 24.6649, 20.9206 ],
	[ 24.9081, 22.8589 ],
	[ 24.9993, 24.8103 ],
	[ 24.9378, 26.7628 ],
	[ 24.7240, 28.7046 ],
	[ 24.3593, 30.6238 ],
	[ 14.6156, 28.3743 ],
	[ 14.9273, 26.4749 ],
	[ 14.9933, 24.5513 ],
	[ 14.8124, 22.6350 ],
	[ 14.3876, 20.7577 ],
	[ 13.7259, 18.9502 ],
	[ 12.8382, 17.2424 ],
	[ 11.7391, 15.6623 ],
	[ 10.4467, 14.2359 ],
	[ 8.9824, 12.9868 ],
	[ 7.3701, 11.9355 ],
	[ 5.6364, 11.0993 ],
	[ 3.8100, 10.4919 ],
	[ 1.9208, 10.1235 ],
	[ -0.0000, 10.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_fj00_Fa000 = ctr_face_fig_demoSheetFold2_SFG_fj00_Fa000_Ctr000;
fig_demoSheetFold2_SFG_fj00 = face_fig_demoSheetFold2_SFG_fj00_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_fj01_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 1.7414, -0.1014 ],
	[ 3.4592, -0.4043 ],
	[ 5.1303, -0.9046 ],
	[ 6.7320, -1.5955 ],
	[ 8.2426, -2.4677 ],
	[ 9.6418, -3.5093 ],
	[ 16.0697, 4.1511 ],
	[ 14.5373, 5.3388 ],
	[ 12.9175, 6.4042 ],
	[ 11.2200, 7.3408 ],
	[ 9.4550, 8.1431 ],
	[ 7.6331, 8.8062 ],
	[ 5.7654, 9.3261 ],
	[ 3.8630, 9.6997 ],
	[ 1.9373, 9.9248 ],
	[ 0.0000, 10.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_fj01_Fa000 = ctr_face_fig_demoSheetFold2_SFG_fj01_Fa000_Ctr000;
fig_demoSheetFold2_SFG_fj01 = face_fig_demoSheetFold2_SFG_fj01_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_fj02_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 1.9397, 0.0754 ],
	[ 3.8678, 0.3010 ],
	[ 5.7725, 0.6756 ],
	[ 7.6424, 1.1968 ],
	[ 9.4662, 1.8615 ],
	[ 11.2330, 2.6657 ],
	[ 12.9320, 3.6046 ],
	[ 14.5531, 4.6725 ],
	[ 16.0864, 5.8629 ],
	[ 17.5227, 7.1687 ],
	[ 18.8534, 8.5821 ],
	[ 20.0704, 10.0944 ],
	[ 21.1664, 11.6966 ],
	[ 22.1348, 13.3789 ],
	[ 22.9698, 15.1314 ],
	[ 23.6662, 16.9434 ],
	[ 24.2200, 18.8039 ],
	[ 24.6277, 20.7018 ],
	[ 24.8870, 22.6256 ],
	[ 24.9962, 24.5637 ],
	[ 14.9977, 24.7382 ],
	[ 14.8384, 22.8044 ],
	[ 14.4309, 20.9074 ],
	[ 13.7819, 19.0788 ],
	[ 12.9022, 17.3494 ],
	[ 11.8067, 15.7479 ],
	[ 10.5136, 14.3012 ],
	[ 9.0446, 13.0336 ],
	[ 7.4243, 11.9662 ],
	[ 5.6797, 11.1169 ],
	[ 3.8401, 10.4999 ],
	[ 1.9363, 10.1255 ],
	[ -0.0000, 10.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_fj02_Fa000 = ctr_face_fig_demoSheetFold2_SFG_fj02_Fa000_Ctr000;
fig_demoSheetFold2_SFG_fj02 = face_fig_demoSheetFold2_SFG_fj02_Fa000;
const ctr_face_fig_demoSheetFold2_SFG_fj03_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 1.9319, -0.1249 ],
	[ 3.8317, -0.4976 ],
	[ 5.6676, -1.1119 ],
	[ 7.4091, -1.9576 ],
	[ 9.0272, -3.0205 ],
	[ 10.4950, -4.2829 ],
	[ 11.7879, -5.7239 ],
	[ 12.8844, -7.3194 ],
	[ 13.7663, -9.0428 ],
	[ 14.4189, -10.8654 ],
	[ 14.8313, -12.7570 ],
	[ 14.9967, -14.6859 ],
	[ 14.9123, -16.6200 ],
	[ 14.5794, -18.5271 ],
	[ 14.0037, -20.3755 ],
	[ 23.3395, -23.9592 ],
	[ 23.9630, -22.1255 ],
	[ 24.4428, -20.2490 ],
	[ 24.7757, -18.3410 ],
	[ 24.9600, -16.4130 ],
	[ 24.9945, -14.4764 ],
	[ 24.8790, -12.5431 ],
	[ 24.6141, -10.6244 ],
	[ 24.2015, -8.7321 ],
	[ 23.6436, -6.8773 ],
	[ 22.9439, -5.0713 ],
	[ 22.1064, -3.3249 ],
	[ 21.1362, -1.6486 ],
	[ 20.0392, -0.0524 ],
	[ 18.8219, 1.4541 ],
	[ 17.4916, 2.8618 ],
	[ 16.0563, 4.1623 ],
	[ 14.5247, 5.3478 ],
	[ 12.9059, 6.4112 ],
	[ 11.2096, 7.3460 ],
	[ 9.4460, 8.1468 ],
	[ 7.6258, 8.8086 ],
	[ 5.7597, 9.3275 ],
	[ 3.8591, 9.7003 ],
	[ 1.9354, 9.9250 ],
	[ -0.0000, 10.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_demoSheetFold2_SFG_fj03_Fa000 = ctr_face_fig_demoSheetFold2_SFG_fj03_Fa000_Ctr000;
fig_demoSheetFold2_SFG_fj03 = face_fig_demoSheetFold2_SFG_fj03_Fa000;

const subpax_SFG_f00 =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 10}, fig_demoSheetFold2_SFG_f00 )
		)
	);


const subpax_SFG_f01 =
	translate( [ 224.35925161963087, -1.491573976280297e-15, 30.623776358596622, ],
		rotate( [ -3.141592653589793, -1.343903524035634, 3.141592653589793, ],
			   extrudeLinear( {height: 10}, fig_demoSheetFold2_SFG_f01 )
		)
	);


const subpax_SFG_f02 =
	translate( [ 203.10228115034502, 10.889807696675593, 138.29826189128397, ],
		rotate( [ -1.2273758443591771, -0.7123930147740429, 0.8334978295521993, ],
			   extrudeLinear( {height: 10}, fig_demoSheetFold2_SFG_f02 )
		)
	);


const subpax_SFG_f03 =
	translate( [ 181.19929063609473, 8.977121768001256, 165.58901364026133, ],
		rotate( [ 2.62387511851185, -0.2728398205700326, 2.642841538225367, ],
			   extrudeLinear( {height: 10}, fig_demoSheetFold2_SFG_f03 )
		)
	);


const subpax_SFG_f04 =
	translate( [ 146.35346234249107, 40.555434529768974, 209.27058884358186, ],
		rotate( [ 0.31222581469686517, -0.6505967922119147, -1.4251759069597367, ],
			   extrudeLinear( {height: 10}, fig_demoSheetFold2_SFG_f04 )
		)
	);


const subpax_SFG_fj00 =
	translate( [ 200, 100, 0, ],
		rotate( [ 1.5707963267948966, 0, 0, ],
			   extrudeLinear( {height: 100}, fig_demoSheetFold2_SFG_fj00 )
		)
	);


const subpax_SFG_fj01 =
	translate( [ 224.3592516196309, 99.99999999999996, 30.62377635859654, ],
		rotate( [ -0.3057724264189251, -0.7268496724933159, 1.7775684666185338, ],
			   extrudeLinear( {height: 141}, fig_demoSheetFold2_SFG_fj01 )
		)
	);


const subpax_SFG_fj02 =
	translate( [ 246.7884187506262, 68.23294335421211, 177.37877077398235, ],
		rotate( [ 2.6505908068656776, -0.9998381681959585, -1.6557359874222042, ],
			   extrudeLinear( {height: 82}, fig_demoSheetFold2_SFG_fj02 )
		)
	);


const subpax_SFG_fj03 =
	translate( [ 224.88542823637593, 66.32025742553773, 204.66952252295968, ],
		rotate( [ -1.8549858579046699, -0.5119809326079411, 2.0516135222243985, ],
			   extrudeLinear( {height: 79}, fig_demoSheetFold2_SFG_fj03 )
		)
	);

const pax_demoSheetFold2 = union( subpax_SFG_f00, subpax_SFG_f01, subpax_SFG_f02, subpax_SFG_f03, subpax_SFG_f04, subpax_SFG_fj00, subpax_SFG_fj01, subpax_SFG_fj02, subpax_SFG_fj03 );

return pax_demoSheetFold2;
}
module.exports = { main };
