// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_maison_faceSide1_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 12.0000, 0.0000 ],
	[ 12.0000, 6.0000 ],
	[ 12.3600, 6.0000 ],
	[ 12.3857, 6.0233 ],
	[ 12.4067, 6.0510 ],
	[ 12.4222, 6.0820 ],
	[ 12.4318, 6.1154 ],
	[ 12.4350, 6.1500 ],
	[ 12.4318, 6.1846 ],
	[ 12.4222, 6.2180 ],
	[ 12.4067, 6.2490 ],
	[ 12.3857, 6.2767 ],
	[ 12.3600, 6.3000 ],
	[ 11.7600, 6.4608 ],
	[ 6.2000, 12.0000 ],
	[ 5.8000, 12.0000 ],
	[ 0.2400, 6.4608 ],
	[ -0.3600, 6.3000 ],
	[ -0.3857, 6.2767 ],
	[ -0.4067, 6.2490 ],
	[ -0.4222, 6.2180 ],
	[ -0.4318, 6.1846 ],
	[ -0.4350, 6.1500 ],
	[ -0.4318, 6.1154 ],
	[ -0.4222, 6.0820 ],
	[ -0.4067, 6.0510 ],
	[ -0.3857, 6.0233 ],
	[ -0.3600, 6.0000 ],
	[ 0.0000, 6.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_maison_faceSide1_Fa000 = ctr_face_fig_maison_faceSide1_Fa000_Ctr000;
fig_maison_faceSide1 = face_fig_maison_faceSide1_Fa000;
const ctr_face_fig_maison_faceSide2_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 12.0000, 0.0000 ],
	[ 12.0000, 6.0000 ],
	[ 12.3600, 6.0000 ],
	[ 12.3857, 6.0233 ],
	[ 12.4067, 6.0510 ],
	[ 12.4222, 6.0820 ],
	[ 12.4318, 6.1154 ],
	[ 12.4350, 6.1500 ],
	[ 12.4318, 6.1846 ],
	[ 12.4222, 6.2180 ],
	[ 12.4067, 6.2490 ],
	[ 12.3857, 6.2767 ],
	[ 12.3600, 6.3000 ],
	[ 11.7600, 6.4608 ],
	[ 6.2000, 12.0000 ],
	[ 5.8000, 12.0000 ],
	[ 0.2400, 6.4608 ],
	[ -0.3600, 6.3000 ],
	[ -0.3857, 6.2767 ],
	[ -0.4067, 6.2490 ],
	[ -0.4222, 6.2180 ],
	[ -0.4318, 6.1846 ],
	[ -0.4350, 6.1500 ],
	[ -0.4318, 6.1154 ],
	[ -0.4222, 6.0820 ],
	[ -0.4067, 6.0510 ],
	[ -0.3857, 6.0233 ],
	[ -0.3600, 6.0000 ],
	[ 0.0000, 6.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_maison_faceSide2_Fa000 = ctr_face_fig_maison_faceSide2_Fa000_Ctr000;
fig_maison_faceSide2 = face_fig_maison_faceSide2_Fa000;
const ctr_face_fig_maison_faceTop1_Fa000_Ctr000 = polygon({ points: [ [ -0.9600, 0.0000 ],
	[ 12.9600, 0.0000 ],
	[ 12.9600, 15.6024 ],
	[ -0.9600, 21.3682 ],
	[ -0.9600, 0.0000 ] ] });

face_fig_maison_faceTop1_Fa000 = ctr_face_fig_maison_faceTop1_Fa000_Ctr000;
fig_maison_faceTop1 = face_fig_maison_faceTop1_Fa000;
const ctr_face_fig_maison_faceTop2_Fa000_Ctr000 = polygon({ points: [ [ -0.9600, -0.3976 ],
	[ 12.9600, 5.3682 ],
	[ 12.9600, 20.9706 ],
	[ -0.9600, 20.9706 ],
	[ -0.9600, -0.3976 ] ] });

face_fig_maison_faceTop2_Fa000 = ctr_face_fig_maison_faceTop2_Fa000_Ctr000;
fig_maison_faceTop2 = face_fig_maison_faceTop2_Fa000;
const ctr_face_fig_maison_faceChimney_Fa000_Ctr000 = polygon({ points: [ [ 5.2500, 1.5000 ],
	[ 6.7500, 1.5000 ],
	[ 6.7500, 2.1000 ],
	[ 5.2500, 2.1000 ],
	[ 5.2500, 1.5000 ] ] });

face_fig_maison_faceChimney_Fa000 = ctr_face_fig_maison_faceChimney_Fa000_Ctr000;
const ctr_face_fig_maison_faceChimney_Fa001_Ctr000 = polygon({ points: [ [ 17.0558, 30.6018 ],
	[ 18.1165, 29.5411 ],
	[ 18.5407, 29.9654 ],
	[ 17.4801, 31.0260 ],
	[ 17.0558, 30.6018 ] ] });

face_fig_maison_faceChimney_Fa001 = ctr_face_fig_maison_faceChimney_Fa001_Ctr000;
const ctr_face_fig_maison_faceChimney_Fa002_Ctr000 = polygon({ points: [ [ 5.1923, 18.4951 ],
	[ 6.5781, 17.9211 ],
	[ 6.8077, 18.4754 ],
	[ 5.4219, 19.0495 ],
	[ 5.1923, 18.4951 ] ] });

face_fig_maison_faceChimney_Fa002 = ctr_face_fig_maison_faceChimney_Fa002_Ctr000;
const ctr_face_fig_maison_faceChimney_Fa003_Ctr000 = polygon({ points: [ [ 5.2500, 10.9353 ],
	[ 6.7500, 10.9353 ],
	[ 6.7500, 11.5353 ],
	[ 5.2500, 11.5353 ],
	[ 5.2500, 10.9353 ] ] });

face_fig_maison_faceChimney_Fa003 = ctr_face_fig_maison_faceChimney_Fa003_Ctr000;
const ctr_face_fig_maison_faceChimney_Fa004_Ctr000 = polygon({ points: [ [ 10.3841, 23.9300 ],
	[ 11.4447, 22.8693 ],
	[ 11.8690, 23.2936 ],
	[ 10.8083, 24.3543 ],
	[ 10.3841, 23.9300 ] ] });

face_fig_maison_faceChimney_Fa004 = ctr_face_fig_maison_faceChimney_Fa004_Ctr000;
fig_maison_faceChimney = union( face_fig_maison_faceChimney_Fa000, face_fig_maison_faceChimney_Fa001, face_fig_maison_faceChimney_Fa002, face_fig_maison_faceChimney_Fa003, face_fig_maison_faceChimney_Fa004 );

const subpax_maison_top1 =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 12}, fig_maison_faceTop1 )
		)
	);


const subpax_maison_side1 =
	translate( [ 0, 21.36820776835531, 0, ],
		rotate( [ 1.5707963267948966, 0, 0, ],
			   extrudeLinear( {height: 21.36820776835531}, fig_maison_faceSide1 )
		)
	);


const subpax_maison_top2 =
	translate( [ 0, 20.97056274847714, 0, ],
		rotate( [ 0, 0, -0.7853981633974483, ],
			   extrudeLinear( {height: 12}, fig_maison_faceTop2 )
		)
	);


const subpax_maison_side2 =
	translate( [ 14.828427124746188, 35.79898987322333, 0, ],
		rotate( [ 1.5707963267948966, 0, -0.7853981633974483, ],
			   extrudeLinear( {height: 21.36820776835531}, fig_maison_faceSide2 )
		)
	);


const subpax_maison_chi1 =
	translate( [ 0, 0, 6, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 7.5}, fig_maison_faceChimney )
		)
	);

const ipax_maison_1 = intersect( subpax_maison_top1, subpax_maison_side1 );
const ipax_maison_2 = intersect( subpax_maison_top2, subpax_maison_side2 );
const pax_maison = union( ipax_maison_1, ipax_maison_2, subpax_maison_chi1 );

return pax_maison;
}
module.exports = { main };
