// Generated by Parametrix
ca_cabane_plancher_facePlancherTop_000 = [ [ 0.0000, 0.0000 ],[ 800.6000, 0.0000 ],[ 800.6000, 200.0000 ],[ 0.0000, 200.0000 ],[ 0.0000, 0.0000 ] ];
cb_cabane_plancher_facePlancherTop_000 = [  0, 1, 2, 3, 4 ];
ca_cabane_plancher_facePlancherTop_001 = [ [ 0.0000, 200.2000 ],[ 800.6000, 200.2000 ],[ 800.6000, 400.2000 ],[ 0.0000, 400.2000 ],[ 0.0000, 200.2000 ] ];
cb_cabane_plancher_facePlancherTop_001 = [  5, 6, 7, 8, 9 ];
ca_cabane_plancher_facePlancherTop_002 = [ [ 0.0000, 400.4000 ],[ 800.6000, 400.4000 ],[ 800.6000, 600.4000 ],[ 0.0000, 600.4000 ],[ 0.0000, 400.4000 ] ];
cb_cabane_plancher_facePlancherTop_002 = [  10, 11, 12, 13, 14 ];
ca_cabane_plancher_facePlancherTop_003 = [ [ 0.0000, 600.6000 ],[ 800.6000, 600.6000 ],[ 800.6000, 800.6000 ],[ 0.0000, 800.6000 ],[ 0.0000, 600.6000 ] ];
cb_cabane_plancher_facePlancherTop_003 = [  15, 16, 17, 18, 19 ];
ca_cabane_plancher_facePlancherTop_004 = [ [ 0.0000, 800.8000 ],[ 800.6000, 800.8000 ],[ 800.6000, 1000.8000 ],[ 0.0000, 1000.8000 ],[ 0.0000, 800.8000 ] ];
cb_cabane_plancher_facePlancherTop_004 = [  20, 21, 22, 23, 24 ];
ca_cabane_plancher_facePlancherTop_005 = [ [ 0.0000, 1001.0000 ],[ 800.6000, 1001.0000 ],[ 800.6000, 1201.0000 ],[ 0.0000, 1201.0000 ],[ 0.0000, 1001.0000 ] ];
cb_cabane_plancher_facePlancherTop_005 = [  25, 26, 27, 28, 29 ];
ca_cabane_plancher_facePlancherTop_006 = [ [ 0.0000, 1201.2000 ],[ 800.6000, 1201.2000 ],[ 800.6000, 1401.2000 ],[ 0.0000, 1401.2000 ],[ 0.0000, 1201.2000 ] ];
cb_cabane_plancher_facePlancherTop_006 = [  30, 31, 32, 33, 34 ];
a_cabane_plancher_facePlancherTop = concat(ca_cabane_plancher_facePlancherTop_000, ca_cabane_plancher_facePlancherTop_001, ca_cabane_plancher_facePlancherTop_002, ca_cabane_plancher_facePlancherTop_003, ca_cabane_plancher_facePlancherTop_004, ca_cabane_plancher_facePlancherTop_005, ca_cabane_plancher_facePlancherTop_006);
b_cabane_plancher_facePlancherTop = [cb_cabane_plancher_facePlancherTop_000, cb_cabane_plancher_facePlancherTop_001, cb_cabane_plancher_facePlancherTop_002, cb_cabane_plancher_facePlancherTop_003, cb_cabane_plancher_facePlancherTop_004, cb_cabane_plancher_facePlancherTop_005, cb_cabane_plancher_facePlancherTop_006];
ca_cabane_plancher_facePlancherBottom_000 = [ [ 0.0000, 0.0000 ],[ 200.0000, 0.0000 ],[ 200.0000, 1401.2000 ],[ 0.0000, 1401.2000 ],[ 0.0000, 0.0000 ] ];
cb_cabane_plancher_facePlancherBottom_000 = [  0, 1, 2, 3, 4 ];
ca_cabane_plancher_facePlancherBottom_001 = [ [ 200.2000, 0.0000 ],[ 400.2000, 0.0000 ],[ 400.2000, 1401.2000 ],[ 200.2000, 1401.2000 ],[ 200.2000, 0.0000 ] ];
cb_cabane_plancher_facePlancherBottom_001 = [  5, 6, 7, 8, 9 ];
ca_cabane_plancher_facePlancherBottom_002 = [ [ 400.4000, 0.0000 ],[ 600.4000, 0.0000 ],[ 600.4000, 1401.2000 ],[ 400.4000, 1401.2000 ],[ 400.4000, 0.0000 ] ];
cb_cabane_plancher_facePlancherBottom_002 = [  10, 11, 12, 13, 14 ];
ca_cabane_plancher_facePlancherBottom_003 = [ [ 600.6000, 0.0000 ],[ 800.6000, 0.0000 ],[ 800.6000, 1401.2000 ],[ 600.6000, 1401.2000 ],[ 600.6000, 0.0000 ] ];
cb_cabane_plancher_facePlancherBottom_003 = [  15, 16, 17, 18, 19 ];
a_cabane_plancher_facePlancherBottom = concat(ca_cabane_plancher_facePlancherBottom_000, ca_cabane_plancher_facePlancherBottom_001, ca_cabane_plancher_facePlancherBottom_002, ca_cabane_plancher_facePlancherBottom_003);
b_cabane_plancher_facePlancherBottom = [cb_cabane_plancher_facePlancherBottom_000, cb_cabane_plancher_facePlancherBottom_001, cb_cabane_plancher_facePlancherBottom_002, cb_cabane_plancher_facePlancherBottom_003];
ca_cabane_plancher_faceBeam_000 = [ [ 200.0000, 800.0000 ],[ 350.0000, 800.0000 ],[ 350.0000, 675.9808 ],[ 335.0000, 650.0000 ],[ 200.0000, 650.0000 ],[ 200.0000, 800.0000 ] ];
cb_cabane_plancher_faceBeam_000 = [  0, 1, 2, 3, 4, 5 ];
ca_cabane_plancher_faceBeam_001 = [ [ 1201.2000, 800.0000 ],[ 1051.2000, 800.0000 ],[ 1051.2000, 675.9808 ],[ 1066.2000, 650.0000 ],[ 1201.2000, 650.0000 ],[ 1201.2000, 800.0000 ] ];
cb_cabane_plancher_faceBeam_001 = [  6, 7, 8, 9, 10, 11 ];
a_cabane_plancher_faceBeam = concat(ca_cabane_plancher_faceBeam_000, ca_cabane_plancher_faceBeam_001);
b_cabane_plancher_faceBeam = [cb_cabane_plancher_faceBeam_000, cb_cabane_plancher_faceBeam_001];
ca_cabane_plancher_faceLeg_000 = [ [ 594.8076, 800.0000 ],[ 421.6025, 800.0000 ],[ -40.2777, 0.0000 ],[ 132.9274, 0.0000 ],[ 594.8076, 800.0000 ] ];
cb_cabane_plancher_faceLeg_000 = [  0, 1, 2, 3, 4 ];
ca_cabane_plancher_faceLeg_001 = [ [ 806.3924, 800.0000 ],[ 979.5975, 800.0000 ],[ 1441.4777, 0.0000 ],[ 1268.2726, 0.0000 ],[ 806.3924, 800.0000 ] ];
cb_cabane_plancher_faceLeg_001 = [  5, 6, 7, 8, 9 ];
a_cabane_plancher_faceLeg = concat(ca_cabane_plancher_faceLeg_000, ca_cabane_plancher_faceLeg_001);
b_cabane_plancher_faceLeg = [cb_cabane_plancher_faceLeg_000, cb_cabane_plancher_faceLeg_001];
ca_cabane_plancher_faceButtress_000 = [ [ 594.8076, 800.0000 ],[ 806.3924, 800.0000 ],[ 892.9949, 650.0000 ],[ 508.2051, 650.0000 ],[ 594.8076, 800.0000 ] ];
cb_cabane_plancher_faceButtress_000 = [  0, 1, 2, 3, 4 ];
a_cabane_plancher_faceButtress = concat(ca_cabane_plancher_faceButtress_000);
b_cabane_plancher_faceButtress = [cb_cabane_plancher_faceButtress_000];
ca_cabane_plancher_faceSide_000 = [ [ 200.0000, 0.0000 ],[ 300.0000, 0.0000 ],[ 300.0000, 800.0000 ],[ 200.0000, 800.0000 ],[ 200.0000, 0.0000 ] ];
cb_cabane_plancher_faceSide_000 = [  0, 1, 2, 3, 4 ];
ca_cabane_plancher_faceSide_001 = [ [ 500.6000, 0.0000 ],[ 600.6000, 0.0000 ],[ 600.6000, 800.0000 ],[ 500.6000, 800.0000 ],[ 500.6000, 0.0000 ] ];
cb_cabane_plancher_faceSide_001 = [  5, 6, 7, 8, 9 ];
a_cabane_plancher_faceSide = concat(ca_cabane_plancher_faceSide_000, ca_cabane_plancher_faceSide_001);
b_cabane_plancher_faceSide = [cb_cabane_plancher_faceSide_000, cb_cabane_plancher_faceSide_001];

module subpax_cabane_plancher_plancherTop () {
	translate( [ 0, 0, 820 ])
		rotate( [ 0, 0, 0 ])
			   linear_extrude(height = 20) polygon(a_cabane_plancher_facePlancherTop, b_cabane_plancher_facePlancherTop);
}

module subpax_cabane_plancher_plancherBottom () {
	translate( [ 0, 0, 800 ])
		rotate( [ 0, 0, 0 ])
			   linear_extrude(height = 20) polygon(a_cabane_plancher_facePlancherBottom, b_cabane_plancher_facePlancherBottom);
}

module subpax_cabane_plancher_beam () {
	translate( [ 800.6, 1401.2, 0 ])
		rotate( [ 90, 0, -90 ])
			   linear_extrude(height = 800.6) polygon(a_cabane_plancher_faceBeam, b_cabane_plancher_faceBeam);
}

module subpax_cabane_plancher_leg1 () {
	translate( [ 300, 1401.2, 0 ])
		rotate( [ 90, 0, -90 ])
			   linear_extrude(height = 100) polygon(a_cabane_plancher_faceLeg, b_cabane_plancher_faceLeg);
}

module subpax_cabane_plancher_leg2 () {
	translate( [ 600.6, 1401.2, 0 ])
		rotate( [ 90, 0, -90 ])
			   linear_extrude(height = 100) polygon(a_cabane_plancher_faceLeg, b_cabane_plancher_faceLeg);
}

module subpax_cabane_plancher_buttress1 () {
	translate( [ 300, 1401.2, 0 ])
		rotate( [ 90, 0, -90 ])
			   linear_extrude(height = 100) polygon(a_cabane_plancher_faceButtress, b_cabane_plancher_faceButtress);
}

module subpax_cabane_plancher_buttress2 () {
	translate( [ 600.6, 1401.2, 0 ])
		rotate( [ 90, 0, -90 ])
			   linear_extrude(height = 100) polygon(a_cabane_plancher_faceButtress, b_cabane_plancher_faceButtress);
}

module pax_cabane_plancher () {
	union () {
		subpax_cabane_plancher_plancherTop();
subpax_cabane_plancher_plancherBottom();
subpax_cabane_plancher_beam();
subpax_cabane_plancher_leg1();
subpax_cabane_plancher_leg2();
subpax_cabane_plancher_buttress1();
subpax_cabane_plancher_buttress2();
	}
}

pax_cabane_plancher();
