// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_codeExample1_faceExample1_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 40.0000, 0.0000 ],
	[ 50.0000, 17.3205 ],
	[ 51.6671, 18.3268 ],
	[ 53.1898, 19.5406 ],
	[ 54.5425, 20.9414 ],
	[ 55.7022, 22.5056 ],
	[ 56.6496, 24.2069 ],
	[ 57.3686, 26.0166 ],
	[ 57.8471, 27.9042 ],
	[ 58.0770, 29.8378 ],
	[ 58.0545, 31.7850 ],
	[ 57.7799, 33.7128 ],
	[ 57.2580, 35.5888 ],
	[ 56.4974, 37.3814 ],
	[ 55.5109, 39.0604 ],
	[ 54.3153, 40.5974 ],
	[ 52.9307, 41.9666 ],
	[ 51.3803, 43.1448 ],
	[ 49.6904, 44.1123 ],
	[ 47.8894, 44.8527 ],
	[ 46.0076, 45.3536 ],
	[ 44.0768, 45.6065 ],
	[ 42.1296, 45.6071 ],
	[ 40.1986, 45.3555 ],
	[ 38.3165, 44.8558 ],
	[ 36.5150, 44.1166 ],
	[ 34.8245, 43.1502 ],
	[ 33.2734, 41.9729 ],
	[ 31.8879, 40.6046 ],
	[ 30.6913, 39.0684 ],
	[ 29.7038, 37.3900 ],
	[ 28.9420, 35.5980 ],
	[ 28.4188, 33.7223 ],
	[ 28.1430, 31.7946 ],
	[ 28.0753, 31.4110 ],
	[ 27.9345, 31.0477 ],
	[ 27.7259, 30.7186 ],
	[ 27.4575, 30.4362 ],
	[ 27.1394, 30.2113 ],
	[ 26.7838, 30.0522 ],
	[ 26.4040, 29.9651 ],
	[ 26.0146, 29.9533 ],
	[ 25.6303, 30.0172 ],
	[ 25.2657, 30.1544 ],
	[ 23.5022, 30.9103 ],
	[ 21.6692, 31.4774 ],
	[ 19.7869, 31.8493 ],
	[ 17.8760, 32.0219 ],
	[ 15.9575, 31.9935 ],
	[ 14.0526, 31.7642 ],
	[ 12.1821, 31.3367 ],
	[ 10.3668, 30.7155 ],
	[ 8.6265, 29.9076 ],
	[ 6.9804, 28.9219 ],
	[ 5.4466, 27.7691 ],
	[ 4.0420, 26.4620 ],
	[ 2.7821, 25.0149 ],
	[ 1.6807, 23.4439 ],
	[ 0.7499, 21.7661 ],
	[ 0.0000, 20.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_codeExample1_faceExample1_Fa000 = ctr_face_fig_codeExample1_faceExample1_Fa000_Ctr000;
fig_codeExample1_faceExample1 = face_fig_codeExample1_faceExample1_Fa000;

const subpax_codeExample1_example1 =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 5}, fig_codeExample1_faceExample1 )
		)
	);

const pax_codeExample1 = subpax_codeExample1_example1;

return pax_codeExample1;
}
module.exports = { main };
