// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_lens_x3_faceLensSim_Fa000_Ctr000 = polygon({ points: [ [ 4.0000, 0.0000 ],
	[ 3.9637, 1.9039 ],
	[ 3.8550, 3.8050 ],
	[ 3.6740, 5.7006 ],
	[ 3.4209, 7.5879 ],
	[ 3.0961, 9.4642 ],
	[ 2.7001, 11.3268 ],
	[ 2.2335, 13.1729 ],
	[ 1.6970, 15.0000 ],
	[ 1.6970, 20.0000 ],
	[ -0.6228, 20.0000 ],
	[ -0.6228, 15.0000 ],
	[ -1.4044, 13.2272 ],
	[ -2.0866, 11.4138 ],
	[ -2.6675, 9.5654 ],
	[ -3.1453, 7.6877 ],
	[ -3.5183, 5.7865 ],
	[ -3.7857, 3.8676 ],
	[ -3.9464, 1.9367 ],
	[ -4.0000, 0.0000 ],
	[ -3.9464, -1.9367 ],
	[ -3.7857, -3.8676 ],
	[ -3.5183, -5.7865 ],
	[ -3.1453, -7.6877 ],
	[ -2.6675, -9.5654 ],
	[ -2.0866, -11.4138 ],
	[ -1.4044, -13.2272 ],
	[ -0.6228, -15.0000 ],
	[ -0.6228, -20.0000 ],
	[ 1.6970, -20.0000 ],
	[ 1.6970, -15.0000 ],
	[ 2.2335, -13.1729 ],
	[ 2.7001, -11.3268 ],
	[ 3.0961, -9.4642 ],
	[ 3.4209, -7.5879 ],
	[ 3.6740, -5.7006 ],
	[ 3.8550, -3.8050 ],
	[ 3.9637, -1.9039 ],
	[ 4.0000, 0.0000 ] ] });

face_fig_lens_x3_faceLensSim_Fa000 = ctr_face_fig_lens_x3_faceLensSim_Fa000_Ctr000;
const ctr_face_fig_lens_x3_faceLensSim_Fa001_Ctr000 = polygon({ points: [ [ 24.0000, 0.0000 ],
	[ 23.9637, 1.9039 ],
	[ 23.8550, 3.8050 ],
	[ 23.6740, 5.7006 ],
	[ 23.4209, 7.5879 ],
	[ 23.0961, 9.4642 ],
	[ 22.7001, 11.3268 ],
	[ 22.2335, 13.1729 ],
	[ 21.6970, 15.0000 ],
	[ 21.6970, 20.0000 ],
	[ 16.0000, 20.0000 ],
	[ 16.0000, 0.0000 ],
	[ 16.0000, -20.0000 ],
	[ 21.6970, -20.0000 ],
	[ 21.6970, -15.0000 ],
	[ 22.2335, -13.1729 ],
	[ 22.7001, -11.3268 ],
	[ 23.0961, -9.4642 ],
	[ 23.4209, -7.5879 ],
	[ 23.6740, -5.7006 ],
	[ 23.8550, -3.8050 ],
	[ 23.9637, -1.9039 ],
	[ 24.0000, 0.0000 ] ] });

face_fig_lens_x3_faceLensSim_Fa001 = ctr_face_fig_lens_x3_faceLensSim_Fa001_Ctr000;
const ctr_face_fig_lens_x3_faceLensSim_Fa002_Ctr000 = polygon({ points: [ [ 44.0000, 0.0000 ],
	[ 43.9637, 1.9039 ],
	[ 43.8550, 3.8050 ],
	[ 43.6740, 5.7006 ],
	[ 43.4209, 7.5879 ],
	[ 43.0961, 9.4642 ],
	[ 42.7001, 11.3268 ],
	[ 42.2335, 13.1729 ],
	[ 41.6970, 15.0000 ],
	[ 41.6970, 20.0000 ],
	[ 32.6228, 20.0000 ],
	[ 32.6228, 15.0000 ],
	[ 33.4044, 13.2272 ],
	[ 34.0866, 11.4138 ],
	[ 34.6675, 9.5654 ],
	[ 35.1453, 7.6877 ],
	[ 35.5183, 5.7865 ],
	[ 35.7857, 3.8676 ],
	[ 35.9464, 1.9367 ],
	[ 36.0000, -0.0000 ],
	[ 35.9464, -1.9367 ],
	[ 35.7857, -3.8676 ],
	[ 35.5183, -5.7865 ],
	[ 35.1453, -7.6877 ],
	[ 34.6675, -9.5654 ],
	[ 34.0866, -11.4138 ],
	[ 33.4044, -13.2272 ],
	[ 32.6228, -15.0000 ],
	[ 32.6228, -20.0000 ],
	[ 41.6970, -20.0000 ],
	[ 41.6970, -15.0000 ],
	[ 42.2335, -13.1729 ],
	[ 42.7001, -11.3268 ],
	[ 43.0961, -9.4642 ],
	[ 43.4209, -7.5879 ],
	[ 43.6740, -5.7006 ],
	[ 43.8550, -3.8050 ],
	[ 43.9637, -1.9039 ],
	[ 44.0000, 0.0000 ] ] });

face_fig_lens_x3_faceLensSim_Fa002 = ctr_face_fig_lens_x3_faceLensSim_Fa002_Ctr000;
fig_lens_x3_faceLensSim = union( face_fig_lens_x3_faceLensSim_Fa000, face_fig_lens_x3_faceLensSim_Fa001, face_fig_lens_x3_faceLensSim_Fa002 );
const ctr_face_fig_lens_x3_faceLens1_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 4.0000 ],
	[ -1.9039, 3.9637 ],
	[ -3.8050, 3.8550 ],
	[ -5.7006, 3.6740 ],
	[ -7.5879, 3.4209 ],
	[ -9.4642, 3.0961 ],
	[ -11.3268, 2.7001 ],
	[ -13.1729, 2.2335 ],
	[ -15.0000, 1.6970 ],
	[ -20.0000, 1.6970 ],
	[ -20.0000, -0.6228 ],
	[ -15.0000, -0.6228 ],
	[ -13.2272, -1.4044 ],
	[ -11.4138, -2.0866 ],
	[ -9.5654, -2.6675 ],
	[ -7.6877, -3.1453 ],
	[ -5.7865, -3.5183 ],
	[ -3.8676, -3.7857 ],
	[ -1.9367, -3.9464 ],
	[ -0.0000, -4.0000 ],
	[ 0.0000, 4.0000 ] ] });

face_fig_lens_x3_faceLens1_Fa000 = ctr_face_fig_lens_x3_faceLens1_Fa000_Ctr000;
fig_lens_x3_faceLens1 = face_fig_lens_x3_faceLens1_Fa000;
const ctr_face_fig_lens_x3_faceLens2_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 4.0000 ],
	[ -1.9039, 3.9637 ],
	[ -3.8050, 3.8550 ],
	[ -5.7006, 3.6740 ],
	[ -7.5879, 3.4209 ],
	[ -9.4642, 3.0961 ],
	[ -11.3268, 2.7001 ],
	[ -13.1729, 2.2335 ],
	[ -15.0000, 1.6970 ],
	[ -20.0000, 1.6970 ],
	[ -20.0000, -4.0000 ],
	[ -0.0000, -4.0000 ],
	[ 0.0000, 4.0000 ] ] });

face_fig_lens_x3_faceLens2_Fa000 = ctr_face_fig_lens_x3_faceLens2_Fa000_Ctr000;
fig_lens_x3_faceLens2 = face_fig_lens_x3_faceLens2_Fa000;
const ctr_face_fig_lens_x3_faceLens3_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 4.0000 ],
	[ -1.9039, 3.9637 ],
	[ -3.8050, 3.8550 ],
	[ -5.7006, 3.6740 ],
	[ -7.5879, 3.4209 ],
	[ -9.4642, 3.0961 ],
	[ -11.3268, 2.7001 ],
	[ -13.1729, 2.2335 ],
	[ -15.0000, 1.6970 ],
	[ -20.0000, 1.6970 ],
	[ -20.0000, -7.3772 ],
	[ -15.0000, -7.3772 ],
	[ -13.2272, -6.5956 ],
	[ -11.4138, -5.9134 ],
	[ -9.5654, -5.3325 ],
	[ -7.6877, -4.8547 ],
	[ -5.7865, -4.4817 ],
	[ -3.8676, -4.2143 ],
	[ -1.9367, -4.0536 ],
	[ -0.0000, -4.0000 ],
	[ 0.0000, 4.0000 ] ] });

face_fig_lens_x3_faceLens3_Fa000 = ctr_face_fig_lens_x3_faceLens3_Fa000_Ctr000;
fig_lens_x3_faceLens3 = face_fig_lens_x3_faceLens3_Fa000;

const subpax_lens_x3_lens1 =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeRotate( {segments: 32}, fig_lens_x3_faceLens1 )
		)
	);


const subpax_lens_x3_lens2 =
	translate( [ 0, 0, 20, ],
		rotate( [ 0, 0, 0, ],
			   extrudeRotate( {segments: 32}, fig_lens_x3_faceLens2 )
		)
	);


const subpax_lens_x3_lens3 =
	translate( [ 0, 0, 40, ],
		rotate( [ 0, 0, 0, ],
			   extrudeRotate( {segments: 32}, fig_lens_x3_faceLens3 )
		)
	);

const pax_lens_x3 = union( subpax_lens_x3_lens1, subpax_lens_x3_lens2, subpax_lens_x3_lens3 );

return pax_lens_x3;
}
module.exports = { main };
